---
title: "Untitled"
format: html
editor: source
---


## Setup
```{r}
library(qs)
library(ArchR)
library(Seurat)
library(tidyverse)
library(cowplot)
library(ComplexHeatmap)
library(circlize)
library(scales)
library(ggrepel)
library(scCustomize)
library(ComplexUpset)
library(patchwork)
library(ggdensity)
library(ggrastr)
library(plyranges)
library(rtracklayer)
library(memes)
library(BSgenome.LStriataDom.Brainard.lonStrDom2.ucsc)
source("../../scripts/common_aesthetics.R")
source(here::here("config/paths.R"))
pnames = names(position_colors)
names(position_colors) = case_when(pnames == "nido" ~ "nr",
                                     pnames == "ncl" ~ "nc",
                                     TRUE ~ pnames)

pnames2 = names(position_colors2)
names(position_colors2) = case_when(pnames2 == "nido" ~ "nr",
                                   pnames2 == "ncl" ~ "nc",
                                   TRUE ~ pnames2)

select = dplyr::select
```

```{r}
meme_db = JASPAR_MEME_DB
options(meme_bin = "/opt/meme/bin",
        meme_db = meme_db
)
check_meme_install()
```


```{r}
proj_dir = "~/ssd/rstudio/multiome/motor-pathway/archr/motor-pathway_archr_processing_cluster-snrna-cr//"
analysis_prefix = "~/ssd/rstudio/multiome/motor-pathway/archr/motor-pathway_archr_processing_cluster-snrna-cr/"
out_name = "dreme"
out_dir = file.path(analysis_prefix, out_name)
dir.create(out_dir, recursive = T)
```

```{r}
#proj = loadArchRProject(proj_dir)
```
## Load GTF
```{r}
gtf = read_gff2(GTF_LONSTR_SLIM)
gtf_gene = gtf[gtf$type=="gene"]
```

```{r}
genes = c("MAFB", "EMX2")
to_extend = 150000

gtf_gene_ex = gtf_gene %>%
  anchor_5p() %>%
  stretch(to_extend)
```

```{r}
gene_df = data.frame(gene = c("MAFB", "EMX2"), 
                     comparision_ct = c("gaba", "astro"))
```

## MAFB 

### Load differential peaks
```{r}
markers_peaks_glut_fname = file.path(proj_dir, "peaks", "peaks_nonsong_glut_se.rds")
marker_peaks_sns_glut = readRDS(markers_peaks_glut_fname)

markers_peaks_gaba_se_fname = file.path(proj_dir, "peaks", "peaks_gaba_se.rds")
marker_peaks_gaba = readRDS(markers_peaks_gaba_se_fname)
```

```{r}
marker_peaks_sns_glut_gr = map(marker_peaks_sns_glut, function(peaks_cur) {
  gr = getMarkers(peaks_cur, cutOff = "FDR <= 0.1", returnGR=T)
  gr
})

marker_peaks_gaba_gr = map(marker_peaks_gaba, function(peaks_cur) {
  gr = getMarkers(peaks_cur, cutOff = "FDR <= 0.1", returnGR=T)
  gr
})
```

### Load peak2genes
```{r}

cor_thresh = 0.25
p2g_fnames = list(ra = sprintf("peak2geneLinks_ra_corCutOff-%s.bed", cor_thresh),
                  gaba = sprintf("peak2geneLinks_gaba_corCutOff-%s.bed", cor_thresh))
p2g_fnames = map(p2g_fnames, ~file.path(proj_dir, "peaks2geneslinks", .x))
p2g_list = map(p2g_fnames, read_delim, col_names=NULL)

p2g_list_gr = map(p2g_list, function(p2g) {
  p2g =  p2g %>% 
    mutate(seqnames = str_extract(X17, "^chr[0-9A-Z]+"),
           start = as.integer(str_extract(X17, "_([0-9]+)-", group = T)),
           end = as.integer(str_extract(X17, "[0-9]+$"))) %>% 
    # rename(seqnames = X17,
    #        start = X18, 
    #        end = X19) %>% 
    as_granges() %>%
    mutate(region = sprintf("%s:%s-%s", seqnames, start, end))
})

p2g_gr = bind_ranges(p2g_list_gr)

gene_cur = "MAFB"


p2g_gr_sel = p2g_gr[p2g_gr$X12==gene_cur,]


```

### Set up sequences
```{r}
marker_peaks_ra = marker_peaks_sns_glut_gr[["ra"]][[1]]
marker_peaks_ra$region = sprintf("%s:%s-%s", seqnames(marker_peaks_ra), start(marker_peaks_ra), end(marker_peaks_ra))
marker_peaks_gaba1 = join_overlap_intersect(marker_peaks_gaba_gr[[1]][[1]], marker_peaks_gaba_gr[[2]][[1]])
marker_peaks_gaba1$region = sprintf("%s:%s-%s", seqnames(marker_peaks_gaba1), start(marker_peaks_gaba1), end(marker_peaks_gaba1))

marker_peaks_ra_gaba_inter = join_overlap_intersect(marker_peaks_ra, marker_peaks_gaba1)
marker_peaks_ra_only =  marker_peaks_ra[!(marker_peaks_ra$region %in% marker_peaks_gaba1$region)]
marker_peaks_gaba1_only =  marker_peaks_gaba1[!(marker_peaks_gaba1$region %in% marker_peaks_ra$region)]

length(marker_peaks_ra_only) / length(marker_peaks_ra)
length(marker_peaks_gaba1_only) / length(marker_peaks_gaba1)
length(marker_peaks_ra_gaba_inter) / length(marker_peaks_ra)
```

```{r}
gtf_gene_ex_cur = gtf_gene_ex[which(gtf_gene_ex$Name==gene_cur)]
gtf_gene_cur = gtf_gene[which(gtf_gene$Name==gene_cur)]
```


```{r}
peaks_list = list(ra_only = marker_peaks_ra_only, 
                  gaba_only = marker_peaks_gaba1_only#, 
                  #ra_gaba_inter = marker_peaks_ra_gaba_inter
                  )

peaks_list_sub =  map(peaks_list, function(x) {
    x[x$region %in% p2g_gr_sel$region]
  })

# peaks_list_sub = map(peaks_list, function(x) {
#   x %>%
#     filter_by_overlaps(gtf_gene_ex_cur) %>%
#     filter_by_non_overlaps(gtf_gene_cur)
# })

peaks_list_sub_fa = map(peaks_list_sub, function(peak) peak %>% get_sequence(BSgenome.LStriataDom.Brainard.lonStrDom2.ucsc))
```

### AME
```{r}
ame_out_ra = runAme(peaks_list_sub_fa[[1]]$ra_only, control = peaks_list_sub_fa[[1]]$gaba_only)
```

```{r}
ame_out_gaba = runAme(peaks_list_sub_fa[[1]]$gaba_only, control = peaks_list_sub_fa[[1]]$ra_only)
```

```{r}
ame_out_ra = ame_out_ra %>%
  mutate(set = "ra")
ame_out_gaba = ame_out_gaba %>%
  mutate(set = "gaba")

ame_out = bind_rows(ame_out_ra, ame_out_gaba)
ame_out = ame_out %>%
  mutate(motif_alt_id = toupper(motif_alt_id)) %>% 
  group_by(set, motif_alt_id) %>% 
  summarize(adj.pvalue = mean(adj.pvalue),
            evalue = mean(evalue)) %>%
  mutate(evalue_log10 = -1 * log10(evalue))

ame_out_f = ame_out %>%
  filter(evalue < 1E-25) %>%
  group_by(set) %>%
  slice_max(order_by=evalue_log10, n=25)


ame_out_w = ame_out %>%
  filter(motif_alt_id %in% ame_out_f$motif_alt_id) %>% 
  select(motif_alt_id, evalue_log10, set) %>%
  pivot_wider(names_from = "set", values_from = "evalue_log10", values_fill = 0) %>%
  column_to_rownames("motif_alt_id") %>%
  as.matrix()

size_factor = 0.1
height = nrow(ame_out_w) * size_factor
width = 1
hm = Heatmap(ame_out_w, 
             height = unit(height, "in"),
             width = unit(width, "in"),
             row_names_gp = gpar(fontsize=6))
hm
```
### FIMO
```{r}
fimo_ra = runFimo(peaks_list_sub_fa$ra_only, motifs=meme_db, thresh=1 )
fimo_gaba = runFimo(peaks_list_sub_fa$gaba_only, motifs=meme_db, thresh=1)
```

```{r fig.height=15}
fimo_ra_df = as.data.frame(fimo_ra) %>%
  mutate(set = "ra")
fimo_gaba_df = as.data.frame(fimo_gaba) %>%
  mutate(set = "gaba")
fimo_df = bind_rows(fimo_ra_df, fimo_gaba_df) %>%
    mutate(motif_alt_id = toupper(motif_alt_id)) 

fimo_df_top = fimo_df %>%
  group_by(set) %>%
  slice_min(order_by = pvalue, n=40)

fimo_df_mat = fimo_df %>%
 # filter(pvalue < 1E-5) %>%
  filter(motif_alt_id %in% fimo_df_top$motif_alt_id) %>% 
  group_by(motif_alt_id, set) %>%
  filter(score==max(score)) %>%
  #summarize(score = mean(score)) %>%
  distinct(motif_alt_id, set, score) %>%
  pivot_wider(names_from="set", values_from="score", values_fill=0) %>%
  column_to_rownames("motif_alt_id") %>%
  as.matrix()
  #ungroup() %>% 
  #arrange(set, score) %>%
  #mutate(motif_alt_id = factor(motif_alt_id, levels=unique(motif_alt_id)))
```
```{r fig.height = 10}
scale_factor = .1
width = 0.5
height = nrow(fimo_df_mat) * scale_factor
colors = brewer_pal("seq", palette=6)(9)
col = colorRamp2(seq(min(fimo_df_mat), max(fimo_df_mat), length.out=9), colors)
hm = Heatmap(fimo_df_mat, 
             col=col,
             cluster_columns = F,
             show_row_dend = F,
             height = unit(height, "in"),
             width = unit(width, "in"))
hm
pdf(file.path(out_dir, str_interp("fimo_${gene_cur}.pdf")), height=height+2, width=width+2)
print(hm)
dev.off()
```

```{r}
fimo_mat_bin = fimo_df %>%
  filter(pvalue < 1E-6) %>%
  #filter(motif_alt_id %in% fimo_df_top$motif_alt_id) %>% 
  group_by(motif_alt_id, set) %>%
  filter(score==max(score)) %>%
  mutate(pvalue_sig = as.integer(pvalue < 1E-5)) %>%
  #summarize(score = mean(score)) %>%
  distinct(motif_alt_id, set, pvalue_sig) %>%
  pivot_wider(names_from="set", values_from="pvalue_sig", values_fill=0) %>%
  column_to_rownames("motif_alt_id") %>%
  as.matrix()


```

```{r fig.height = 10}
scale_factor = .25
width = 4
height = ncol(fimo_mat_bin) * scale_factor
colors = brewer_pal("seq", palette=6)(9)
col = colorRamp2(c(0, 1), c("white", "black"))
hm = Heatmap(t(fimo_mat_bin), 
             col=col,
             cluster_rows = F,
             show_column_dend = F,
             height = unit(height, "in"),
             rect_gp = gpar(col="white", lwd=1),
             column_names_gp = gpar(fontsize=6),
             width = unit(width, "in"))
hm
pdf(file.path(out_dir, str_interp("fimo_${gene_cur}_binary.pdf")), height=height+2, width=width+2)
print(hm)
dev.off()
```

## EMX2 
### Load differential peaks
```{r}
markers_peaks_glut_fname = file.path(proj_dir, "peaks", "peaks_nonsong_glut_se.rds")
marker_peaks_sns_glut = readRDS(markers_peaks_glut_fname)

markers_peaks_astro_se_fname = file.path(proj_dir, "peaks", "peaks_astro_se.rds")
marker_peaks_astro = readRDS(markers_peaks_astro_se_fname)
```

```{r}
marker_peaks_sns_glut_gr = map(marker_peaks_sns_glut, function(peaks_cur) {
  gr = getMarkers(peaks_cur, cutOff = "FDR <= 0.1", returnGR=T)
  gr
})

marker_peaks_astro_gr = map(marker_peaks_astro, function(peaks_cur) {
  gr = getMarkers(peaks_cur, cutOff = "FDR <= 0.1", returnGR=T)
  gr
})
```


### Load peak2genes
```{r}

cor_thresh = 0.25
p2g_fnames = list(ra = sprintf("peak2geneLinks_ra_corCutOff-%s.bed", cor_thresh),
                  astro = sprintf("peak2geneLinks_neuroglia_corCutOff-%s.bed", cor_thresh))
p2g_fnames = map(p2g_fnames, ~file.path(proj_dir, "peaks2geneslinks", .x))
p2g_list = map(p2g_fnames, read_delim, col_names=NULL)

p2g_list_gr = map(p2g_list, function(p2g) {
  p2g =  p2g %>% 
    mutate(seqnames = str_extract(X17, "^chr[0-9A-Z]+"),
           start = as.integer(str_extract(X17, "_([0-9]+)-", group = T)),
           end = as.integer(str_extract(X17, "[0-9]+$"))) %>% 
    # rename(seqnames = X17,
    #        start = X18, 
    #        end = X19) %>% 
    as_granges() %>%
    mutate(region = sprintf("%s:%s-%s", seqnames, start, end))
})

p2g_gr = bind_ranges(p2g_list_gr)

gnee_cur = "EMX2"


p2g_gr_sel = map(genes_to_select, function(gts) {
  p2g_gr[p2g_gr$X12==gts,]
})


```

### Set up sequences
```{r}
marker_peaks_ra = marker_peaks_sns_glut_gr[["ra"]][[1]]
marker_peaks_ra$region = sprintf("%s:%s-%s", seqnames(marker_peaks_ra), start(marker_peaks_ra), end(marker_peaks_ra))
marker_peaks_astro1 = bind_ranges(marker_peaks_astro_gr[[1]][[1]], marker_peaks_astro_gr[[2]][[1]])
marker_peaks_astro1$region = sprintf("%s:%s-%s", seqnames(marker_peaks_astro1), start(marker_peaks_astro1), end(marker_peaks_astro1))

marker_peaks_ra_astro_inter = join_overlap_intersect(marker_peaks_ra, marker_peaks_astro1)
marker_peaks_ra_only =  marker_peaks_ra[!(marker_peaks_ra$region %in% marker_peaks_astro1$region)]
marker_peaks_astro1_only =  marker_peaks_astro1[!(marker_peaks_astro1$region %in% marker_peaks_ra$region)]

length(marker_peaks_ra_only) / length(marker_peaks_ra)
length(marker_peaks_astro1_only) / length(marker_peaks_astro1)
length(marker_peaks_ra_astro_inter) / length(marker_peaks_ra)
```

```{r}
gtf_gene_ex_cur = gtf_gene_ex[which(gtf_gene_ex$Name==gene_cur)]
gtf_gene_cur = gtf_gene[which(gtf_gene$Name==gene_cur)]
```


```{r}
peaks_list = list(ra_only = marker_peaks_ra_only,
                  astro_only = marker_peaks_astro1_only#,
                  #ra_astro_inter = marker_peaks_ra_astro_inter
                  )

# peaks_list_sub = map(peaks_list, function(x) {
#   x %>% filter_by_overlaps(p2g_gr_sel[[1]])
#    # x[x$region %in% p2g_gr_sel[[1]]$region]
# })

peaks_list_sub = map(peaks_list, function(x) {
  x %>%
    filter_by_overlaps(gtf_gene_ex_cur) %>%
    filter_by_non_overlaps(gtf_gene_cur)
})

peaks_list_sub_fa = map(peaks_list_sub, function(peak) peak %>% get_sequence(BSgenome.LStriataDom.Brainard.lonStrDom2.ucsc)) %>%
  set_names(names(peaks_list))
```

### AME
```{r}
ame_out_ra = runAme(peaks_list_sub_fa$ra_only)
```

```{r}
ame_out_astro = runAme(peaks_list_sub_fa$astro_only, control = peaks_list_sub_fa$ra_only)
```

```{r}
ame_out_ra = ame_out_ra %>%
  mutate(set = "ra")
ame_out_astro = ame_out_astro %>%
  mutate(set = "astro")

ame_out = bind_rows(ame_out_ra, ame_out_astro)
ame_out = ame_out %>%
  mutate(motif_alt_id = toupper(motif_alt_id)) %>% 
  group_by(set, motif_alt_id) %>% 
  summarize(adj.pvalue = mean(adj.pvalue),
            evalue = mean(evalue)) %>%
  mutate(evalue_log10 = -1 * log10(evalue))

ame_out_f = ame_out %>%
  filter(evalue < 1E-25) %>%
  group_by(set) %>%
  slice_max(order_by=evalue_log10, n=25)


ame_out_w = ame_out %>%
  filter(motif_alt_id %in% ame_out_f$motif_alt_id) %>% 
  select(motif_alt_id, evalue_log10, set) %>%
  pivot_wider(names_from = "set", values_from = "evalue_log10", values_fill = 0) %>%
  column_to_rownames("motif_alt_id") %>%
  as.matrix()

size_factor = 0.1
height = nrow(ame_out_w) * size_factor
width = 1
hm = Heatmap(ame_out_w, 
             height = unit(height, "in"),
             width = unit(width, "in"),
             row_names_gp = gpar(fontsize=6))
hm
```

### FIMO
```{r}
fimo_ra = runFimo(peaks_list_sub_fa$ra_only, motifs=meme_db, thresh=1 )
fimo_astro = runFimo(peaks_list_sub_fa$astro_only, motifs=meme_db, thresh=1)
```

```{r fig.height=15}
fimo_ra_df = as.data.frame(fimo_ra) %>%
  mutate(set = "ra")
fimo_astro_df = as.data.frame(fimo_astro) %>%
  mutate(set = "astro")
fimo_df = bind_rows(fimo_ra_df, fimo_astro_df) %>%
    mutate(motif_alt_id = toupper(motif_alt_id)) 

fimo_df_top = fimo_df %>%
  group_by(set) %>%
  slice_min(order_by = pvalue, n=40)

fimo_df_mat = fimo_df %>%
 # filter(pvalue < 1E-5) %>%
  filter(motif_alt_id %in% fimo_df_top$motif_alt_id) %>% 
  group_by(motif_alt_id, set) %>%
  filter(score==max(score)) %>%
  #summarize(score = mean(score)) %>%
  distinct(motif_alt_id, set, score) %>%
  pivot_wider(names_from="set", values_from="score", values_fill=0) %>%
  column_to_rownames("motif_alt_id") %>%
  as.matrix()
  #ungroup() %>% 
  #arrange(set, score) %>%
  #mutate(motif_alt_id = factor(motif_alt_id, levels=unique(motif_alt_id)))
```
```{r fig.height = 10}
scale_factor = .1
width = 0.5
height = nrow(fimo_df_mat) * scale_factor
colors = brewer_pal("seq", palette=6)(9)
col = colorRamp2(seq(min(fimo_df_mat), max(fimo_df_mat), length.out=9), colors)
hm = Heatmap(fimo_df_mat, 
             col=col,
             cluster_columns = F,
             show_row_dend = F,
             height = unit(height, "in"),
             width = unit(width, "in"))
hm
pdf(file.path(out_dir, stt_interp("fimo_${gene_cur}.pdf")), height=height+2, width=width+2)
print(hm)
dev.off()
```


