---
title: "Untitled"
format: html
editor: source
---



## Setup
```{r}
library(qs)
library(ArchR)
library(Seurat)
library(furrr)
library(tidyverse)
library(cowplot)
library(ComplexHeatmap)
library(circlize)
library(scales)
library(ggrepel)
library(scCustomize)

source("../../scripts/common_aesthetics.R")
source(here::here("config/paths.R"))
pnames = names(position_colors)
names(position_colors) = case_when(pnames == "nido" ~ "nr",
                                     pnames == "ncl" ~ "nc",
                                     TRUE ~ pnames)

pnames2 = names(position_colors2)
names(position_colors2) = case_when(pnames2 == "nido" ~ "nr",
                                   pnames2 == "ncl" ~ "nc",
                                   TRUE ~ pnames2)
```


```{r}
proj_dir = "~/ssd/rstudio/multiome/motor-pathway/archr/motor-pathway_archr_processing_cluster-snrna-cr/"
script_name = "export_for_homer"
out_dir = here::here("multiome/archr", script_name)
dir.create(out_dir, recursive = T)

addArchRThreads(threads = 36) 
```

```{r}
proj = loadArchRProject(proj_dir)
```

## Differential peaks
```{r}
plan(multisession(workers = 4))
```

```{r}
pair_list = list(
  ra_arco = list("Glut-RA", "Glut-Arco-1"),
  astro1_oligo = list("Astro-1", "Oligo"),
  astro2_oligo = list("Astro-2", "Oligo")
)
```

```{r}
markers_peaks_astro_se_fname = file.path(out_dir, "peaks_se.rds")
markers_peaks_astro_fname = file.path(out_dir, "peaks.rds")

redo = T
if (redo) {
  
  marker_peaks_astro = map(pair_list, \(pair_cur) {
      print(pair_cur)
      getMarkerFeatures(
        ArchRProj = proj, 
        useMatrix = "PeakMatrix", 
        groupBy = "cluster",
        useGroups = pair_cur[[1]],
        bgdGroups = pair_cur[[2]],
        bias = c("TSSEnrichment", "log10(nFrags)"),
        testMethod = "wilcoxon"
      )
  }) %>% set_names(names(pair_list))
  
  saveRDS(marker_peaks_astro, markers_peaks_astro_se_fname)
  
  marker_peaks_astro_gr = map(marker_peaks_astro, function(peaks_cur) {
    gr = getMarkers(peaks_cur, cutOff = "FDR <= 0.1", returnGR=T)
    gr
  })
  
  marker_peaks_astro_df = map(marker_peaks_astro_gr, as.data.frame) %>%
    bind_rows( .id="comparison")
  saveRDS(marker_peaks_astro_df, markers_peaks_astro_fname)
} else {
  marker_peaks_astro = readRDS(markers_peaks_astro_se_fname)
  marker_peaks_astro_df = readRDS(markers_peaks_astro_fname)
}

 marker_peaks_astro_gr = map(marker_peaks_astro, function(peaks_cur) {
    gr = getMarkers(peaks_cur, cutOff = "FDR <= 0.1", returnGR=T)
    gr
  })


```
```{r}
marker
```

