---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(SeuratWrappers)
library(tidyverse)
library(rtracklayer)
library(SeuratDisk)
library(BiocParallel)
library(cowplot)
library(qs)
library(furrr)
theme_set(theme_bw())

source(here::here("scripts/scRNA.R"))
source(here::here("config/paths.R"))
```
## Directory setup
```{r}
out_dir = "~/hdd/rstudio/snRNA/snrna_cellranger/preprocessing/snrna_cellranger_preprocess"
#prefix
dir.create(out_dir, recursive = T)
```

```{r}
samples_to_process = c("ra_run1", "arco_run1", "hvc_run1", "nc_run1", "nc_run2", "lman", "nr")
ds = map_chr(samples_to_process, ~ sprintf("~/ssd/snRNA/210607_snrna/%s/outs/filtered_feature_bc_matrix", .x))  # edit path to match local CellRanger output
names(ds) = samples_to_process
out_dirs = map(samples_to_process, function(samp) file.path(out_dir, samp))
walk(out_dirs, dir.create)
out_fnames = map(samples_to_process, function(samp) file.path(out_dir, samp, "obj.qs"))

```

## Create Seurat Object

Load MT data
```{r}
tx = import(GTF_LONSTR_NCBI)
  tx_trans = tx[tx$type=="transcript"]
  tx_rrna = tx_trans[grep("ribosomal RNA", tx_trans$product)]
  tx_mt = tx_trans[seqnames(tx_trans)=="NC_029475.1"]
  tx_mt$gene_id = sub("_", "-", tx_mt$gene_id)
  tx_mt$gene_id = sub("gene-", "", tx_mt$gene_id)
```

```{r}
redo_sct = F

objs = map(seq_along(ds), function(i) {
  input_fname = ds[[i]]
  print(input_fname)
  sample_to_process = samples_to_process[i]
  out_fname = out_fnames[[i]]
  ssplit = str_split(sample_to_process, "_")[[1]]
  position = ssplit[1]
  run = ssplit[2]
  if (redo_sct) {
    
    dat = Read10X(data.dir = input_fname)
    obj = CreateSeuratObject(counts = dat, project = "snRNA")
    
    
    
    to_flag = intersect(rownames(obj), tx_mt$gene_id)
    obj = PercentageFeatureSet(obj, features=to_flag, col.name="perc_mito")
    
    obj$species = "BF"
    obj$position = position
    obj$run =  run
    
    obj = SCTransform(obj, vars.to.regress = "perc_mito", return.only.var.genes = F) 
    qsave(obj, out_fname )
  } else {
    obj = qread(out_fname)
  }
  return(obj)
})
```
## QC
```{r}
objs = map(objs, function(obj) {
  to_flag = intersect(rownames(obj), tx_mt$gene_id)
  PercentageFeatureSet(obj, features=to_flag, col.name="perc_mito")
})
```

```{r fig.width=10}
features = c("nFeature_RNA", "nCount_RNA", "perc_mito")

walk(objs, function(obj) {
  obj$sample = paste(obj$position, obj$run, sep="_")
  print(VlnPlot(obj, features=features, pt.size = 0))
})
```

```{r}
min_feature = 1000
max_count = 20000
max_perc_mito = 2

objs_filt = map(objs, function(obj) {
  
  cells = Cells(obj)[(obj$nFeature_RNA > min_feature) & (obj$nCount_RNA < max_count) & (obj$perc_mito < max_perc_mito)]
  obj_filt = subset(obj, cells=cells)
  obj_filt
})
```

```{r fig.width=10}

walk(objs_filt, function(obj) {
  obj$sample = paste(obj$position, obj$run, sep="_")
  print(VlnPlot(obj, features=features, pt.size = 0))
})
```
```{r}
objs_filt
```
## Dim reduction
```{r}
dims_use = 1:30
objs_filt = map(objs_filt, function(obj) {
  obj %>%
    RunPCA() %>%
    RunUMAP(dims = dims_use)
})
```

## Cluster
```{r}
ress = seq(.1, .6, .1)
objs_filt = map(objs_filt, function(obj) {
 seurat_find_clusters(obj, ress, dims.use=dims_use, 
                       algorithm = 2, 
                       cluster_prefix = "cluster",
                       reduction = "pca", 
                       assay="SCT")
})
```

## Doublet finding
```{r}
library(DoubletFinder)

#plan(multisession(workers = length(objs_filt)))
objs_singlet = map(objs_filt, function(obj) {
  print(unique(obj$position))
  sweep.res.list_obj <- paramSweep(obj, PCs = dims_use, sct = T, num.cores = 10)
  sweep.stats_obj <- summarizeSweep(sweep.res.list_obj, GT = FALSE)
  bcmvn_obj <- find.pK(sweep.stats_obj)
  pK = bcmvn_obj$pK[which.max(bcmvn_obj$BCmetric)]
  
  nExp <- round(ncol(obj) * 0.07)  # expect 7% doublets
  #homotypic.prop <- modelHomotypic()  
  obj = DoubletFinder::doubletFinder(obj, pN = 0.25, pK = as.numeric(pK), nExp = nExp, PCs = dims_use, sct=T)
 # obj <- doubletFinder(obj, PCs = dims_use, pN = 0.25, pK = as.numeric(pK), nExp = nExp_poi.adj, sct = FALSE)
  DF.name = colnames(obj@meta.data)[grepl("DF.classification", colnames(obj@meta.data))]
  
  print(cowplot::plot_grid(ncol = 1,DimPlot(obj, group.by = DF.name) + NoAxes()))
  print(VlnPlot(obj, features = "nFeature_RNA", group.by = DF.name, pt.size = 0.1))
  
  obj[, obj@meta.data[, DF.name] == "Singlet"]
})
```

```{r}
obj1 = objs_singlet[[1]]
features = c("SIX2", "CRHR2", "NDNF", "CRHR1", "SLC17A6", "TBR1", "LOC110476696", "CRHBP")
FeaturePlot(obj1, features, reduction = "umap")
DimPlot(obj1, reduction="umap")
DotPlot(obj1, features=features, group.by = "cluster.0.6")
```
```{r fig.height=8}
obj1 = obj_kb
features = c( "CRHR2", "CRHR1", "LOC110476696", "CRHBP", "CRH")
FeaturePlot(obj1, features, reduction = "umap")
DimPlot(obj1, reduction="umap")
DotPlot(obj1, features=features)
```
```{r}
obj_cr = objs_singlet[[1]]
obj_cr_avg = AverageExpression(obj_cr, group.by = "cluster.0.6")[["SCT"]]
obj_cr_avg_ra = obj_cr_avg[,c('g0', 'g1', 'g6', 'g11')]
obj_cr_avg_ra = apply(obj_cr_avg_ra, 1, mean)
obj_cr_avg_ra_df = data.frame(gene = names(obj_cr_avg_ra), cr = obj_cr_avg_ra)

obj_kb_avg = AverageExpression(obj_kb, group.by="cluster")[["SCT"]]
obj_kb_avg_ra = obj_kb_avg[,"Glut-RA"]
obj_kb_avg_ra_df = data.frame(gene = names(obj_kb_avg_ra), kb = obj_kb_avg_ra)

df = obj_cr_avg_ra_df %>% left_join(obj_kb_avg_ra_df)
df = df %>% mutate(kb_log = log1p(kb),
                   cr_log = log1p(cr),
                   kb_sub_cr = kb_log - cr_log)
```

```{r}
ggplot(df, aes(log1p(cr), log1p(kb))) + 
  geom_point()
```


```{r}
walk(seq_along(ds), function(i) {
  out_fname = out_fnames[[i]]
  qsave(objs_singlet[[i]], out_fname )
})
```

