# config/paths.R
#
# Central configuration for all external data paths.
# Source this file near the top of each analysis script:
#
#   source(here::here("config/paths.R"))
#
# Then edit the path variables below to match your local environment.
# See data/README.md for download instructions for reference files.
#
# Bundled data (data/ directory) is resolved automatically via here::here().
# External reference data paths must be set manually below.

library(here)

# ---------------------------------------------------------------------------
# Bengalese finch (lonStrDom2 / GCF_005870125.1) reference assembly
# Source: NCBI RefSeq — https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_005870125.1/
# ---------------------------------------------------------------------------

# Genome FASTA (UCSC chromosome names)
GENOME_FA_LONSTR   <- "/mnt/nest/assembly/lonStrDom2/ncbi/GCF_005870125.1_lonStrDom2_genomic_ucsc_only.fna"

# Chromosome sizes (generate: samtools faidx <genome.fna>; cut -f1,2 <fai> > chrom.sizes)
CHROM_SIZES_LONSTR <- "/mnt/nest/assembly/lonStrDom2/ucsc/chrom.sizes.ucsc"

# GTF — merged StringTie + RefSeq annotation (slim form, UCSC chromosome names)
# Custom GTF combining RefSeq with StringTie-assembled transcripts; contact the
# Colquitt lab or regenerate from the raw StringTie outputs.
GTF_LONSTR_SLIM    <- "/mnt/nest/assembly/lonStrDom2/ncbi/merge_gtf_with_3p/GCF_005870125.1_lonStrDom2_genomic_stringtie_FPKMthresh0.5_FPKMmaxfrac0.1_minhits5_slim_ucsc.gtf"

# GTF — full form (used for DREME/DREME-TFBS)
GTF_LONSTR_FULL    <- "/mnt/nest/assembly/lonStrDom2/ncbi/merge_gtf_with_3p/GCF_005870125.1_lonStrDom2_genomic_stringtie_FPKMthresh0.5_FPKMmaxfrac0.1_minhits5_ucsc.gtf"

# GTF — NCBI chromosome names (no UCSC renaming; used for CellRanger preprocessing
# where mitochondrial transcripts are identified by the NCBI contig name NC_029475.1)
GTF_LONSTR_NCBI    <- "/mnt/nest/assembly/lonStrDom2/ncbi/merge_gtf_with_3p/GCF_005870125.1_lonStrDom2_genomic_stringtie_FPKMthresh0.5_FPKMmaxfrac0.1_minhits5.gtf"

# GTF — with gene_biotype field (used for Seurat/SnapATAC2 annotation import)
GTF_LONSTR_BIOTYPE <- "/mnt/nest/assembly/lonStrDom2/ncbi/merge_gtf_with_3p/GCF_005870125.1_lonStrDom2_genomic_stringtie_FPKMthresh0.5_FPKMmaxfrac0.1_minhits5_ucsc_gene-biotype.gtf"

# ---------------------------------------------------------------------------
# Chicken (bGalGal1.mat / GCF_016699485.2) reference assembly
# Source: NCBI RefSeq — https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_016699485.2/
#         Ensembl 112 — https://useast.ensembl.org/Gallus_gallus/
# Note: this GTF has custom MAFB/EMX2 transgene annotations appended to the
# standard Ensembl 112 Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.112 annotation.
# ---------------------------------------------------------------------------

GTF_CHICKEN_MAFB_EMX2 <- "/mnt/nest/assembly/bGalGal1.mat/addons/Gallus_gallus.bGalGal1.mat.broiler.GRCg7b.112.chr.ucsc_ppidnb2-mafb_v2_emx2.gtf"

# ---------------------------------------------------------------------------
# JASPAR motif database
# Source: JASPAR 2022 — https://jaspar.elixir.lu/downloads/
#   Download: JASPAR2022_CORE_vertebrates_non-redundant_v2.meme
# ---------------------------------------------------------------------------

JASPAR_MEME_DB <- "/hdd/brad/meme/motif_databases/JASPAR/JASPAR2022_CORE_vertebrates_non-redundant_v2.meme"

# ---------------------------------------------------------------------------
# cisTarget motif databases (used for SCENIC+ cisTarget database creation)
# Source: SCENIC+ resources — https://resources.aertslab.org/cistarget/
#   Download: v10nr_clust_public/ (non-redundant clustered motifs)
# ---------------------------------------------------------------------------

CISTARGET_SINGLETONS_DIR <- "/home/brad/nest/cistarget/v10nr_clust_public/singletons"

# ---------------------------------------------------------------------------
# ArchR genome/gene annotation objects
# Generated by multiome/archr/archr_processing.qmd (createGeneAnnotation step).
# ---------------------------------------------------------------------------

ARCHR_SETUP_DIR <- "~/ssd/rstudio/multiome/archr/setup/"

# ---------------------------------------------------------------------------
# Analysis output directories (generated by running earlier pipeline steps)
# ---------------------------------------------------------------------------

# ArchR project (output of multiome/archr/archr_processing.qmd)
ARCHR_PROJ_DIR      <- "~/ssd/rstudio/multiome/motor-pathway/archr/motor-pathway_archr_processing_cluster-snrna-cr/"

# Multiome Seurat project (output of multiome/seurat/seurat_preprocess.qmd)
MULTIOME_SEURAT_DIR <- "~/ssd/rstudio/multiome/motor-pathway/seurat/motor-pathway_multiome_seurat_cellbender.0.05_preprocess_cr/"

# snRNA-seq Seurat project (output of snrna/clustering/snrna_seurat_cellbender_preprocess.qmd)
SNRNA_SEURAT_DIR    <- "~/hdd/rstudio/snRNA/snrna_cellranger/snrna_seurat_cellbender.0.01_preprocess/"

# SCENIC+ output base directory (output of grn/*/scenicplus/ Snakemake workflows)
SCENICPLUS_BASE_DIR <- "~/ssd/rstudio/multiome/motor-pathway/scenicplus/"

# ---------------------------------------------------------------------------
# Bundled gene lists and ortholog tables (resolved relative to repository root)
# ---------------------------------------------------------------------------

GMT_C5_V7 <- here::here("data/gene_lists/c5.all.v7.0.symbols.gmt")

# OMA zebra finch ↔ chicken 1:1 orthologs (used by snrna/integration/)
OMA_ORTHOLOGS_ZF_CK <- here::here("data/orthologs/oma_orthologs_zf-ck.txt")
