---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(Seurat)
library(BPCells)
library(SeuratDisk)
library(SeuratWrappers)
library(tidyverse)
library(BSgenome.LStriataDom.Brainard.lonStrDom2.ucsc)
library(rtracklayer)
library(GenomicRanges)
library(qs)
library(furrr)
library(cowplot)
library(clustree)
library(scCustomize)

source("../../scripts/scRNA.R")
source(here::here("config/paths.R"))
reticulate::use_condaenv("/home/brad/micromamba/envs/scanorama")
rename = dplyr::rename
select = dplyr::select
```

```{r}
samples_to_process = c("ra_run1", "arco_run1", "hvc_run1", "nc_run1",
                       #"nc_run2", 
                       "lman_run1", "nr_run1")
```

```{r}
base_dir = "/hdd1/brad/snRNA/210607_snrna/"

## Cellbender
cb_dirs = file.path(base_dir, "cellbender", paste(samples_to_process, "lonStrDom2_3p_merge_ucsc", sep="_"))
cb_fnames = map(cb_dirs, list.files, full.names=T, pattern="FPR_0.01_filtered.h5")
names(cb_fnames) = samples_to_process

## Cellranger
cr_dirs = file.path(base_dir, samples_to_process)
#cr_fnames = list.files(cr_dir, pattern="sample.*_ucsc", full.names = T)
feature_h5s = file.path(cr_dirs, "outs", "filtered_feature_bc_matrix.h5")
#atac_frags = file.path(cr_dirs, "outs", "atac_fragments.tsv.gz")

names(feature_h5s) = samples_to_process
#names(atac_frags) = params_table$sample_name


data_dir = file.path(base_dir, "aggr", "outs")
#setup_dir = "~/ssd/rstudio/multiome/archr/setup/"
analysis_prefix = "~/hdd/rstudio/snRNA/snrna_cellranger/"
out_name = "snrna_seurat_cellbender.0.01_preprocess"
out_dir = file.path(analysis_prefix, out_name)
dir.create(out_dir, recursive = T)

feature_h5 = file.path(data_dir, "filtered_feature_bc_matrix.h5")
#atac_frags = file.path(data_dir, "atac_fragments.tsv.gz")

aggr_csv = read_csv(file.path(base_dir, "aggr.csv"))
aggr_csv = aggr_csv[match(samples_to_process, aggr_csv$sample_id),]

#out_split_fname = file.path(out_dir, "obj_position_split.qs")
out_full_fname = file.path(out_dir, "obj.qs")
out_processed_fname = file.path(out_dir, "obj_processed.qs")
out_fname = file.path(out_dir, "obj_clustered.qs")
out_h5_fname = file.path(out_dir, "obj_clustered.h5seurat")

seed = 10
set.seed(seed)
```

## Load gene annotation

```{r}
annotation = rtracklayer::import(GTF_LONSTR_BIOTYPE)
annotation$gene_biotype = if_else(is.na(annotation$gene_biotype), "", annotation$gene_biotype)
annotation$gene_name = annotation$gene

annotation_mt = annotation[seqnames(annotation)=="chrM",]
genes_mt = na.omit(annotation_mt$Name)
```

```{r}
plan(sequential)
```

## Load data

```{r}

redo  = F
if (redo) {
  # objs = mclapply(sample_names, mc.set.seed=F,
  #                 mc.cores=length(sample_names),
  #                 function(sample_name) {
  objs = future_map(samples_to_process,
                    .options = furrr_options(seed=seed),
                    .f = function(sample_name) {

    ## Load CellBender corrected
    cb_fname = cb_fnames[[sample_name]]
    cb_mat = scCustomize::Read_CellBender_h5_Mat(cb_fname)
    #sample_index = str_extract(sample_name, "[0-9]+")
    sample_index = which(aggr_csv$sample_id == sample_name)
    ### Fix barcodes
    bcodes = colnames(cb_mat)
    bcodes = sub("-1", str_interp("-${sample_index}"), bcodes)
    colnames(cb_mat) = bcodes
    
    bp_dir = file.path(out_dir, "bpcells", sample_name, "cellbender")
    write_matrix_dir(
      mat = cb_mat,
      dir = bp_dir, 
      overwrite = T
    )
    
    cb_mat_bp <- open_matrix_dir(dir = bp_dir) 
    
    ## Load CellRanger raw
    feature_h5 = feature_h5s[sample_name]
    cn = Seurat::Read10X_h5(filename = feature_h5)
    #cn_gex = cn$`Gene Expression`
    
    ### Fix barcodes
    bcodes = colnames(cn)
    bcodes = sub("-1", str_interp("-${sample_index}"), bcodes)
    colnames(cn) = bcodes
    
    bp_dir = file.path(out_dir, "bpcells", sample_name, "gex")
    
    write_matrix_dir(
      mat = cn,
      dir = bp_dir, 
      overwrite = T
    )
    cr_mat_bp <- open_matrix_dir(dir = bp_dir)

    obj = scCustomize::Create_CellBender_Merged_Seurat(raw_cell_bender_matrix = cb_mat_bp, 
                                          raw_counts_matrix = cr_mat_bp,
                                          raw_assay_name = "RAW")
    obj$sample_name = sample_name
    obj
  })


  obj = scCustomize::Merge_Seurat_List(objs)
  obj = JoinLayers(obj)
  
  qsave(obj, out_full_fname)
} else {
  obj = qread(out_full_fname)
}
```

## Add perc mito

```{r}
annotation_trans = annotation[annotation$type=="transcript"]
annotation_mt = annotation_trans[seqnames(annotation_trans)=="chrM"]

annotation_mt$gene_id = sub("_", "-", annotation_mt$gene_id)
annotation_mt$gene_id = sub("gene-", "", annotation_mt$gene_id)
DefaultAssay(obj) = "RNA"
to_flag = intersect(rownames(obj), annotation_mt$gene_id)
obj =  PercentageFeatureSet(obj, features=to_flag, col.name="perc_mito")
```

```{r}
Idents(obj) = obj$sample_name
VlnPlot(obj, "perc_mito")
```

## Filter

```{r}
VlnPlot_scCustom(obj, c("perc_mito", "nCount_RNA"), pt.size=0)
```

```{r}
obj_filt = 
  subset(x = obj,
  subset = 
    perc_mito < 2 &
    nCount_RNA < 20000 &
    nCount_RNA > 1000 

  )

gg = VlnPlot_scCustom(
  obj_filt, 
  features = c("nCount_RNA", "perc_mito"),
  pt.size = 0
)
print(gg)

```

```{r}
obj = obj_filt
```

## Load souporcell

```{r}
soc_dirs = file.path(base_dir, samples_to_process)
names(soc_dirs) = samples_to_process

soc_dirs = soc_dirs[samples_to_process]
soc_cluster_fnames = map(soc_dirs, ~file.path(.x, "souporcell", "clusters.tsv"))
soc_clusters = map(soc_cluster_fnames, read_delim)
soc_clusters = map(seq_along(soc_clusters), function(i) {
  soc_cur = soc_clusters[[i]]
  #soc_cur = soc_cur %>% mutate(barcode = paste(barcode, i, sep="_"))
  soc_cur = soc_cur %>% mutate(barcode = sub("1", i, barcode))
  soc_cur
}) %>% bind_rows()
soc_clusters = soc_clusters %>%
  mutate(barcode = paste0("_", barcode))
soc_clusters = soc_clusters %>% column_to_rownames("barcode")
soc_clusters = soc_clusters %>% 
  select(status, assignment) %>%
  rename(doublet_status = status)
soc_clusters = soc_clusters[Cells(obj),]
```

```{r}
table(soc_clusters$assignment)
```

```{r}
obj = AddMetaData(obj, soc_clusters)
```

## Doublet detection

```{r}
md_df_fname = file.path(out_dir, "md_doubletfinder.rds")
redo  = F
if (redo) {
  library(DoubletFinder)
  library(future)
  library(doFuture)
  options(future.globals.maxSize = 50 *1E9)
  obj_list = SplitObject(obj, split.by="sample_name")

  plan(sequential)
  #cl <- makeCluster(length(obj_list))
  #doParallel::registerDoParallel(cl)
  md_list = map(obj_list, function(obj_cur) {
    
    sample_name = obj_cur$sample_name[1]
    print(sample_name)
    # Use uncorrected values
    obj_cur[["RAW"]]$counts <- as(object = obj_cur[["RAW"]]$counts, Class = "dgCMatrix") ## Needed to work with BPCells
    obj_cur[["RNA"]]$counts = obj_cur[["RAW"]]$counts
    DefaultAssay(obj_cur) = "RNA"
    obj_cur <- NormalizeData(obj_cur, verbose = F)
    obj_cur <- FindVariableFeatures(obj_cur, selection.method = "vst", nfeatures = 2000)
    obj_cur <- ScaleData(obj_cur, verbose = F)
    obj_cur <- RunPCA(obj_cur, verbose = F)
    
    sweep.res.list <- paramSweep(obj_cur, PCs = 1:10, sct = F)
    gt.calls <- obj_cur@meta.data[rownames(sweep.res.list[[1]]), "doublet_status"]
    gt.calls = str_to_title(gt.calls) 
    sweep.stats = map(seq_along(sweep.res.list), function(i) {
      tryCatch({
        #sweep.stat <- summarizeSweep(sweep.res.list[i], GT = TRUE, GT.calls = gt.calls)
        sweep.stat <- summarizeSweep(sweep.res.list[i], GT = F)
        sweep.stat
      },
      error = function(cond) {
        data.frame()
      })
    }) %>% set_names(names(sweep.res.list)) %>% bind_rows(.id="pN")
    
    bcmvn <- find.pK(sweep.stats)
    pK = as.numeric(as.character(bcmvn[which.max(bcmvn$BCmetric),]$pK))
    print(sprintf("%s pK = %s", sample_name, pK))
    nExp <- round(ncol(obj_cur) * 0.04) 
    obj_cur = DoubletFinder::doubletFinder(obj_cur, pN = 0.25, pK = pK, nExp = nExp, PCs = 1:10, sct=F)
    DF.name = colnames(obj_cur@meta.data)[grepl("DF.classification", colnames(obj_cur@meta.data))]
    
    # cowplot::plot_grid(ncol = 2, 
    #                    DimPlot(obj_cur, group.by = "position", reduction="umap_rna_int") + NoAxes(),
    #                    DimPlot(obj_cur, group.by = DF.name, reduction="umap_rna_int") + NoAxes())
    # 
    # gg = VlnPlot(obj_cur, features = "nFeature_RNA", group.by = DF.name, pt.size = 0.1)
    # print(gg)
    
    return(obj_cur@meta.data[, c(DF.name, "sample_name")])
  })
  
  md = map(md_list, function(md) {
    names(md) = c("DF_class", "sample_name" )
    md = md %>% rownames_to_column()
    md
  }) %>% bind_rows()
  
  md = md %>% column_to_rownames()
  saveRDS(md, md_df_fname)
  
  rm(obj_list)
} else {
  md = readRDS(md_df_fname)
}
md = md[Cells(obj),]
obj = AddMetaData(obj, md)

```

```{r}
table(obj$doublet_status, obj$DF_class)
# DimPlot_scCustom(obj, group.by="DF_class", reduction="umap_rna_int")
VlnPlot(obj, features = "nFeature_RNA", split.by = "sample_name", group.by = "DF_class", pt.size = 0.1)

#DimPlot_scCustom(obj, group.by="doublet_status", reduction="umap_rna_int")
VlnPlot(obj, features = "nFeature_RNA", group.by = "doublet_status", pt.size = 0.1)
```

## Re-process

```{r}
cells = Cells(obj)[obj$doublet_status=="singlet" & obj$DF_class=="Singlet"]
obj = subset(obj, cells=cells)
```

```{r}
cluster_prefix = "cluster"

rna_dims = 30
redo  = F
if (redo) {
  
  ## GEX
  DefaultAssay(obj) = "RNA"
  
  if (is.null(Layers(obj)))
    obj[["RNA"]] <- split(obj[["RNA"]], f = obj$replicate)
  
   obj <- obj %>%
     SCTransform() %>%
   # NormalizeData(verbose = F) %>%
    #FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>%
    #ScaleData(verbose = T) %>%
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )
  
  #DefaultAssay(obj) = "SCT"
  obj = obj %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.2, 1, .2), 
                         reduction="pca",
                         algorithm = 2,
                         #graph.name = NULL,
                         cluster_prefix = cluster_prefix, 
                         assay="SCT")
  
  
  # # Integrate PCA embeddings
  # obj <- IntegrateLayers(object = obj, 
  #                        method = HarmonyIntegration, 
  #                        orig.reduction = "pca", 
  #                        new.reduction = 'pca_harmony', verbose = FALSE)
  
  
  #obj = JoinLayers(obj)
  
  # obj = obj %>% 
  #   seurat_find_clusters(dims.use=1:rna_dims, 
  #                        ress = seq(.5, 2, .5), 
  #                        reduction="pca_harmony",
  #                        algorithm = 2,
  #                        graph.name = NULL,
  #                        cluster_prefix = paste(cluster_prefix, "pca_harmony", sep="_"), 
  #                        assay="SCT")
  # 
  # 
  # 
  # obj =  RunUMAP(
  #   object = obj,
  #   reduction = "pca_harmony",
  #   reduction.name = "umap_rna_int", 
  #   assay = "RNA",
  #   dims = 1:rna_dims,
  #   verbose = TRUE
  # )
  
  #rm(cn, counts, integration.anchors, obj_list, obj_lsi, obj_pca)
  qsave(obj, out_processed_fname)
} else {
  obj = qread(out_processed_fname)
}
```

```{r}
obj$position = str_extract(obj$sample_name, "([a-z]+)_", group=1)
```

## Plots

```{r}
redo_plot = F
if (redo_plot) {
  reductions = c("umap_rna")
  cats = c("position")
  
  walk(reductions, function(reduction) {
    walk(cats, function(ca) {
      gg = DimPlot(obj, group.by=ca, reduction = reduction) + coord_equal()
      print(gg)
      save_plot(file.path(out_dir, sprintf("umap_int_by_%s_%s.png", reduction, ca)), gg)
    })
    
    
    walk(cats, function(ca) {
      gg = DimPlot(obj, group.by=ca, split.by=ca, reduction = reduction) + coord_equal()
      print(gg)
      save_plot(file.path(out_dir, sprintf("umap_int_split-by_%s_%s.png", reduction, ca)), gg)
    })
  })
}
```

```{r}
if (redo_plot) {
  reduction = "umap_rna"
  ress = grep("cluster", unique(colnames(obj@meta.data)), value = T)
  #ress = grep("harmony", ress, value=T)
  walk(ress, function(res) {
    gg = DimPlot(object = obj, group.by = res, label=T, reduction = reduction)
    gg = gg + labs(title=res)
    save_plot(file.path(out_dir, sprintf("umap_%s.png", res)), gg)
    print(gg)
  })
}
```

```{r}

if (redo_plot) {
  features = c("SLC17A6", "GAD1", "SLC1A2", "CSF1R", "MBP", "PDGFRA", "NECTIN3", "SOX4", "FLI1",
               "SPEF2", "RGS5", "LUM", "NR4A2", "SIX2", "NDNF", "PVALB", "PCP4", "EMX2", "BACH2", "SOX2", "ISL1", "TBR1",
               "EOMES", "FOXP2", "MAFB", "LHX6", "PROX1", "LHX9", "NR2F2", "DACH1", "POU3F2",
               "SATB2", "SATB1", "FEZF2", "BCL11B", "EMX1", "ZBTB20")
  features =  intersect(features, rownames(obj))
  
  reduction = "umap_rna"
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj, features=feat, reduction = reduction) + coord_equal()
    print(gg)
    save_plot(file.path(out_dir, sprintf("umap_%s.png", feat)), gg)
  })
  

}

```

```{r}
DefaultAssay(obj) = "RAW"
reduction = "umap_rna"
walk(features, function(feat) {
  gg = FeaturePlot_scCustom(obj, features=feat, reduction = reduction) + coord_equal()
  print(gg)
  save_plot(file.path(out_dir, sprintf("umap_%s.png", feat)), gg)
})

```

```{r}
res_to_use = "cluster.0.2"
```

```{r fig.height = 10}
DotPlot(obj, features = features, group.by = res_to_use) + coord_flip()
```

```{r}

## FINISH
idents_comb = c(`0`="Glut",
                `1`="GABA",
                `2`="Glut",
                `3`="Glut",
                `4`="Astro",
                `5`="GABA",
                `6`="Glut",
                `7`="Glut",
                `8`="Oligo",
                `9`="Glut",
                `10`="Glut",
                `11`="OPC",
                `12`="GABA",
                `13`="Epen",
                `14`="GABA",
                `15`="Glut",
                `16`="Astro",
                `17`="Glut",
                `18`="Glut",
                `19`="GABA",
                `20`="Glut",
                `21`="GABA",
                `22`="Glut",
                `23`="Astro"
                )

out_cluster_cur = "celltype"
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj@meta.data[,res_to_use], from = names(idents_comb), to = idents_comb)

```

## Glutamatergic

```{r}
glut_dir = file.path(out_dir, "glutamatergic")
dir.create(glut_dir)
```

```{r}
fname_int_ex = file.path(out_dir, "obj_glutamatergic.qs")
dims.use_list = list( 1:20)
rna_dims = 20
names(dims.use_list) = map_chr(dims.use_list, max)
cluster_prefix_cur =  str_interp("${cluster_prefix}_glut")

redo = F
if (redo) {
  cells = Cells(obj)[grepl("Glut", obj$celltype)]
  obj_glut = subset(obj, cells=cells)
  
  obj_glut <- obj_glut %>%
    SCTransform() %>% 
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )
  
  # obj_glut <- IntegrateLayers(object = obj_glut, 
  #                        method = HarmonyIntegration, 
  #                        orig.reduction = "pca",
  #                        new.reduction = 'pca_harmony', verbose = FALSE)
  
  obj_glut = obj_glut %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.3, .8, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")

  qsave(obj_glut, fname_int_ex)
} else {
  obj_glut = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(paste(cluster_prefix_cur, "pca", sep="_"), unique(colnames(obj_glut@meta.data)), value = T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_glut, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })


DimPlot(obj_glut, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_glut, group.by="position", reduction=reduction_cur)
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.5")
```

```{r}
features = c("SOX4", "EOMES", "SPEF2", "SCUBE1", "GFRA1", "CRHR2", "GAD1",
             "LHX9", # Erniched in Arco
             "NR2F2", # Enriched in Arco/Nido
             "DACH1", # Enriched in Nido/Hyper
             "POU3F2", 
             "FOXP1", # Enriched in Meso
             "SATB2", # Enriched in Meso 
             "NEFM",
             "NECTIN3",
             "SLC1A2", "SOX2", "SOX4",
             "SATB1", "FEZF2", "BCL11B", "ZBTB20")
features = unique(features)
redo_plot = F
if (redo_plot) {
  reduction = "umap_rna"
  
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_glut, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(glut_dir, sprintf("umap_%s.png", feat)), gg)
  })
  
  DotPlot(obj_glut, features = features, group.by = res_to_use_sub) + coord_flip()
}
```

```{r}
table(obj_glut$position, obj_glut@meta.data[,res_to_use_sub])
```

```{r}
idents_comb = c(`0`="Glut-Nido",
                `1`="Glut-Nido",
                `2`="Glut-Nido",
                `3`="Glut-Nido",
                `4`="Glut-Arco",
                `5`="Glut-Arco",
                `6`="Glut-Nido",
                `7`="Glut-Nido",
                `8`="Glut-Arco",
                `9`="Glut-Nido",
                `10`="Glut-Nido",
                `11`="Glut-Nido",
                `12`="Glut-Nido",
                `13`="Glut-Nido",
                `14`="Glut-Nido",
                `15`="Glut-Arco",
                `16`="Glut-Nido",
                `17`="Glut-Nido",
                `18`="Glut-Nido",
                `19`="Glut-Arco",
                `20`="Glut-Arco",
                `21`="Glut-Nido",
                `22`="Glut-Nido"
                
                )

out_cluster_cur = str_interp("celltype_n_glut")
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj_glut@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj_glut@meta.data[,res_to_use_sub], from = names(idents_comb), to = idents_comb)
```

```{r}
qsave(obj_glut, fname_int_ex)
```

## Glutamatergic Arco

```{r}
glut_arco_dir = file.path(out_dir, "glutamatergic_arco")
dir.create(glut_arco_dir)
```

```{r}
fname_int_ex = file.path(out_dir, "obj_glutamatergic_arco.qs")
rna_dims = 10
cluster_prefix_cur =  str_interp("${cluster_prefix}_glut_arco")

redo = F
if (redo) {
  #cells = Cells(obj_glut)[obj_glut$position %in% c("ra", "arco")]
  cells = Cells(obj_glut)[grepl("Arco", obj_glut$celltype_n_glut)]
  obj_glut_arco = subset(obj_glut, cells=cells)

  obj_glut_arco <- obj_glut_arco %>%
    SCTransform(vars.to.regress = "perc_mito") %>%
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )
  

  obj_glut_arco = obj_glut_arco %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.3, .8, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")

  qsave(obj_glut_arco, fname_int_ex)
  
} else {
  obj_glut_arco = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_glut_arco@meta.data)), value = T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_glut_arco, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })

DimPlot(obj_glut_arco, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_glut_arco, group.by="position", reduction=reduction_cur)
#DimPlot(obj_glut_arco, group.by="run", reduction=reduction_cur)


```

```{r fig.height=10}
ct_res = clustree::clustree(obj_glut_arco, prefix=paste(cluster_prefix_cur,  "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.5")
```

```{r}
features = c("perc_mito", "nCount_RNA", "SLC17A6", "GAD1", "SLC1A2", "CRHR2", "NR4A2", 
             "FOXP1", "FOXP2", "DACH1", "DACH2", "FEZF2", "SATB1", "SATB2",
             "MTNR1B", "VIPR2", "ADAMTS18", "EMX2", "TBR1", "POU3F2", "EPHB1",
             "MAFB", "NDNF", "SIX2", "PVALB", # Up in RA 
             "LHX9",  "C1QL3",  "EPHA6", "CHRM5", # Down in RA
             "ESR1", "ESR2", "AR", "EGR1", "FOSL2", "ARC",
             "ZBTB20" # Enriched posterior Hyper, HPC and some Arco
             
)
if (redo_plot) {
  reduction = "umap_rna"
  
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_glut_arco, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(glut_arco_dir, sprintf("%s_%s.pdf", reduction, feat)), gg, base_height = 5, base_width = 5)
  })
}
```

```{r fig.height = 8}
DotPlot(obj_glut_arco, features = features, group.by = res_to_use_sub) + coord_flip()
```

```{r}
table(obj_glut_arco@meta.data[,res_to_use_sub], obj_glut_arco$assignment)
```

```{r}
idents_comb = c(`0`="Glut-Arco-1",
                `1`="Glut-RA",
                `2`="Glut-Arco-2",
                `3`="Glut-RA",
                `4`="Glut-Arco-3",
                `5`="Glut-Arco-4",
                `6`="Glut-Arco-5",
                `7`="Glut-Arco-6",
                `8`="Exclude",
                `9`="Glut-Arco-7",
                `10`="Exclude",
                `11`="Glut-RA",
                `12`="Exclude",
                `13`="Exclude"
                )

out_cluster_cur = str_interp("celltype_n_glut_arco")
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj_glut_arco@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj_glut_arco@meta.data[,res_to_use_sub], from = names(idents_comb), to = idents_comb)

table(FetchData(obj_glut_arco, c("position", out_cluster_cur)))
```

### Re-process

```{r}
fname_int_ex = file.path(out_dir, "obj_glutamatergic_arco_filt.qs")
rna_dims = 10
cluster_prefix_cur =  str_interp("${cluster_prefix}_glut_arco")

redo = F
if (redo) {
  cells = Cells(obj_glut_arco)[!grepl("Exclude", obj_glut_arco$celltype_n_glut_arco)]
  obj_glut_arco_filt = subset(obj_glut_arco, cells=cells)

  obj_glut_arco_filt <- obj_glut_arco_filt %>%
    SCTransform(vars.to.regress="perc_mito") %>% 
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )

  obj_glut_arco_filt = obj_glut_arco_filt %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.3, .8, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")
  
  qsave(obj_glut_arco_filt, fname_int_ex)
  
} else {
  obj_glut_arco_filt = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_glut_arco_filt@meta.data)), value = T)
ress = grep("pca", ress, value=T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_glut_arco_filt, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })

DimPlot(obj_glut_arco_filt, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_glut_arco_filt, group.by="position", reduction=reduction_cur)

```

```{r fig.height=10}
ct_res = clustree::clustree(obj_glut_arco_filt, prefix=paste(cluster_prefix_cur,  "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.3")
```

```{r}
features = c( "nCount_RNA", "perc_mito", "SLC17A6", "GAD1", "SLC1A2", "CRHR2", "NR4A2", 
             "FOXP1", "FOXP2", "DACH1", "DACH2", "FEZF2", "SATB1", "SATB2",
             "MTNR1B", "VIPR2", "ADAMTS18", "EMX2", "TBR1", "POU3F2", "EPHB1",  "MAFB", "NDNF", "SIX2", "PVALB", # Up in RA 
             "LHX9",  "C1QL3",  "EPHA6", "CHRM5", # Down in RA
             "ESR1", "ESR2", "AR",
             "ZBTB20" # Enriched posterior Hyper, HPC and some Arco
             
)
if (redo_plot) {
  reduction = "umap_rna"
  
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_glut_arco_filt, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(glut_arco_dir, sprintf("%s_%s.pdf", reduction, feat)), gg, base_height = 5, base_width = 5)
  })
}
```

```{r fig.height = 8}
DotPlot(obj_glut_arco_filt, features = features, group.by = res_to_use_sub) + coord_flip()
```

```{r}
idents_comb = c(`0`="Glut-Arco-1",
                `1`="Glut-Arco-2",
                `2`="Glut-RA",
                `3`="Glut-RA",
                `4`="Glut-Arco-3",
                `5`="Glut-Arco-4",
                `6`="Glut-Arco-5",
                `7`="Glut-RA"
                )

out_cluster_cur = str_interp("celltype_n_glut_arco")
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj_glut_arco_filt@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj_glut_arco_filt@meta.data[,res_to_use_sub], from = names(idents_comb), to = idents_comb)

## Combine with obj_glut
md_cur = FetchData(obj_glut_arco_filt, c("position", out_cluster_cur)) %>%
  mutate(position = case_when(grepl("Glut-RA", !!out_cluster_cur_sym) ~ "ra",
                              !grepl("Glut-RA", !!out_cluster_cur_sym)~ "arco"))
obj_glut_arco_filt = AddMetaData(obj_glut_arco_filt, md_cur)

table(FetchData(obj_glut_arco_filt, c("position", out_cluster_cur)))
```

```{r}
qsave(obj_glut_arco_filt, fname_int_ex)
```

## Glutamatergic Nido

```{r}
glut_nido_dir = file.path(out_dir, "glutamatergic_nido")
dir.create(glut_nido_dir)
```

```{r}
fname_int_ex = file.path(out_dir, "obj_glutamatergic_nido.qs")

rna_dims = 10
names(dims.use_list) = map_chr(dims.use_list, max)
cluster_prefix_cur =  str_interp("${cluster_prefix}_glut_nido")

redo = F
if (redo) {
  cells = Cells(obj_glut)[grepl("Nido", obj_glut$celltype_n_glut)]
  obj_glut_nido = subset(obj_glut, cells=cells)

   obj_glut_nido <- obj_glut_nido %>%
    SCTransform(vars.to.regress="perc_mito") %>% 
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )

  obj_glut_nido = obj_glut_nido %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.3, 1, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")
  
  qsave(obj_glut_nido, fname_int_ex)
  
} else {
  obj_glut_nido = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_glut_nido@meta.data)), value = T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_glut_nido, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })


DimPlot(obj_glut_nido, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_glut_nido, group.by="position", reduction=reduction_cur)
```

```{r fig.height=10}
ct_res = clustree::clustree(obj_glut_nido, prefix=paste(cluster_prefix_cur, "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.7")
```

```{r}
features = c("perc_mito", "nFeature_RNA", "SLC17A6", "GAD1", "PVALB", "ALDH1A2", "CDH9", "DPP6", "ZNF385B", "DPP10", "GFRA1", "KCNK9", "KCNQ5", # HVC
              "SCUBE1", "GABRG3", "TOX", "SYCP1", "ADAMTSL1", "COL12A1", "SLIT3", "GRIA4", "NECTIN3", "SOX4",  # HVC
              "SLC1A2", "SOX2",
              "CALCB" #LMAN
)

if (redo_plot) {
  reduction = "umap_rna"
  DefaultAssay(obj_glut_nido) = "RAW"
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_glut_nido, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(glut_nido_dir, sprintf("umap_%s.pdf", feat)), gg, base_height = 5, base_width = 5)
  })
}

```

```{r}
if (redo_plot) {
  reduction = "umap_rna"
  DefaultAssay(obj_glut_nido) = "SCT"
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_glut_nido, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(glut_nido_dir, sprintf("umap_%s.pdf", feat)), gg, base_height = 5, base_width = 5)
  })
}
```

```{r fig.height=8}
if (redo_plot) {
  DotPlot(obj_glut_nido, features = features, group.by = res_to_use_sub) + coord_flip()
}
```

```{r}
table(FetchData(obj_glut_nido, c("position", res_to_use_sub)))
```

```{r}
table(FetchData(obj_glut_nido, c("assignment", res_to_use_sub)))
```

```{r}
idents_comb = c(`0`="Glut-NC-1",
                `1`="Glut-HVC-1",
                `2`="Glut-HVC-1", 
                `3`="Glut-NC-2",
                `4`="Glut-NR-1",
                `5`="Glut-Pre-3",
                `6`="Glut-LMAN-1",
                `7`="Glut-Nido-1",
                `8`="Glut-NR-2",
                `9`="Glut-NR-3",
                `10`="Glut-NC-3",
                `11`="Glut-LMAN-2",
                `12`="Glut-Nido-2",
                `13`="Glut-Pre-2",
                `14`="Glut-LMAN-2",
                `15`="Glut-NR-4",
                `16`="Glut-HVC-2",
                `17`="Glut-Nido-3",
                `18`="Glut-Nido-4",
                `19`="Glut-NC-4",
                `20`="Exclude",
                `21`="Glut-HVC-1"
                )

out_cluster_cur = str_interp("celltype_n_glut_nido")
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj_glut_nido@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj_glut_nido@meta.data[,res_to_use_sub], from = names(idents_comb), to = idents_comb)

```

```{r}
qsave(obj_glut_nido, fname_int_ex)
```

### Re-process

```{r}
fname_int_ex = file.path(out_dir, "obj_glutamatergic_nido_filt.qs")
rna_dims = 20
#snames(dims.use) = map_chr(dims.use_list, max)
cluster_prefix_cur =  str_interp("${cluster_prefix}_glut_nido")

redo = F
if (redo) {
  cells = Cells(obj_glut_nido)[!grepl("Exclude", obj_glut_nido$celltype_n_glut_nido)]
  obj_glut_nido_filt = subset(obj_glut_nido, cells=cells)

  obj_glut_nido_filt <- obj_glut_nido_filt %>%
    SCTransform(vars.to.regress = "perc_mito") %>% 
    #SCTransform() %>% 
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )

  obj_glut_nido_filt = obj_glut_nido_filt %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.3, 1, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")
  
  qsave(obj_glut_nido_filt, fname_int_ex)
  
} else {
  obj_glut_nido_filt = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_glut_nido_filt@meta.data)), value = T)
ress = grep("pca", ress, value=T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_glut_nido_filt, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })

DimPlot(obj_glut_nido_filt, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_glut_nido_filt, group.by="position", reduction=reduction_cur)

```

```{r fig.height=10}
ct_res = clustree::clustree(obj_glut_nido_filt, prefix=paste(cluster_prefix_cur,  "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.1")
```

```{r}
features = c( "SLC17A6", "GAD1", "PVALB", "ALDH1A2", "CDH9", "DPP6", "ZNF385B", "DPP10", "GFRA1", "KCNK9", "KCNQ5", # HVC
              "SCUBE1", "GABRG3", "TOX", "SYCP1", "ADAMTSL1", "COL12A1", "SLIT3", "GRIA4", "NECTIN3", "SOX4",  # HVC
              "SLC1A2", "SOX2",
              "CALCB" #LMAN
)

if (redo_plot) {
  reduction = "umap_rna"
  DefaultAssay(obj_glut_nido_filt) = "SCT"
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_glut_nido_filt, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(glut_nido_dir, sprintf("umap_%s.pdf", feat)), gg, base_height = 5, base_width = 5)
  })
}

```

```{r}
table(FetchData(obj_glut_nido_filt, c("assignment", res_to_use_sub)))
```

```{r fig.height = 8}
DotPlot(obj_glut_nido_filt, features = features, group.by = res_to_use_sub) + coord_flip()
```

```{r}
table(FetchData(obj_glut_nido_filt, c("position", res_to_use_sub)))
```

```{r}
idents_comb = c(`0`="Glut-HVC-1",
                `1`="Glut-NC-1",
                `2`="Glut-HVC-1",
                `3`="Glut-NR-1",
                `4`="Glut-LMAN-1",
                `5`="Glut-NC-2",
                `6`="Glut-NR-2",
                `7`="Glut-NR-3",
                `8`="Glut-Nido-1",
                `9`="Glut-NC-3",
                `10`="Glut-HVC-1a",
                `11`="Glut-NR-4",
                `12`="Glut-LMAN-2",
                `13`="Glut-Pre-3",
                `14`="Glut-Pre-3",
                `15`="Glut-NR-5",
                `16`="Glut-HVC-2", 
                `17`="Glut-Pre-2", 
                `18`="Glut-Pre-2",
                `19`="Glut-Nido-2",
                `20`="Glut-NC-4",
                `21`="Glut-Nido-3",
                `22`="Glut-NC-1",
                `23`="Exclude",
                `24`="Exclude",
                `25`="Glut-LMAN-2",
                `26`="Exclude",
                `27`="Glut-HVC-1"
                )

out_cluster_cur = str_interp("celltype_n_glut_nido")
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj_glut_nido_filt@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj_glut_nido_filt@meta.data[,res_to_use_sub], from = names(idents_comb), to = idents_comb)

table(FetchData(obj_glut_nido_filt, c("position", out_cluster_cur)))
```

```{r}
gg = DimPlot(object = obj_glut_nido_filt, group.by = out_cluster_cur, label=T, reduction = reduction_cur) + coord_equal()
gg
```

```{r}
qsave(obj_glut_nido_filt, fname_int_ex)

```

## GABAergic

```{r}
gaba_dir = file.path(out_dir, "gabaergic")
dir.create(gaba_dir)
```

```{r}
fname_int_ex = file.path(out_dir, "obj_gabaergic.qs")
dims.use = 10
names(dims.use_list) = map_chr(dims.use_list, max)
cluster_prefix_cur =  str_interp("${cluster_prefix}_gaba")

redo = F
if (redo) {
  cells = Cells(obj)[grepl("GABA", obj$celltype) ]
  obj_gaba = subset(obj, cells=cells)

  obj_gaba <- obj_gaba %>%
    SCTransform(vars.to.regress="perc_mito") %>% 
    # NormalizeData(verbose = F) %>%
    # FindVariableFeatures(selection.method = "vst", nfeatures = 2000) %>%
    # ScaleData(verbose = T) %>%
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )
  

  # obj_gaba <- IntegrateLayers(object = obj_gaba, 
  #                        method = HarmonyIntegration, 
  #                        orig.reduction = "pca", 
  #                        new.reduction = 'pca_harmony', verbose = FALSE)
  
  obj_gaba = obj_gaba %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.1, .8, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")

  qsave(obj_gaba, fname_int_ex)
  
} else {
  obj_gaba = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_gaba@meta.data)), value = T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_gaba, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })

DimPlot(obj_gaba, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_gaba, group.by="position", reduction=reduction_cur)

```

```{r fig.height=10}
ct_res = clustree::clustree(obj_gaba, prefix=paste(cluster_prefix_cur, "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.5")
```

```{r}
if (redo_plot) {
  
  reduction = "umap_rna"
  features = c("nCount_RNA", "nFeature_RNA", "SPEF2", "SLC17A6", "SLC17A7", "SLC17A8", "GAD1", "SLC1A2",  "MBP", "PDGFRA",
               "NECTIN3", "SOX4",
               "CXCR4", # CR
               "ARX", "MAFB", "MAF", "LHX6", "SST", "NPY", "NXPH1",  "SOX6", "SATB1",  ## MGE
                "CEMIP", "PHACTR2", "COL24A1", # GABA-3
               "TTLL5", "LPP", # GABA-4
               "LHX8", # GABA-8 
               "CALB2", # GABA-7
               "LAMP5", "CCK",  "VIP",
               "PROX1", "NR2F2", "ADARB2", "CNR1", "RELN", # CGE
               "FOXP1", "TSHZ1", "ZFHX4", # LGE
               "MEIS2", "SORCS3", "IQSEC1", "TRPM3", "LRP1B", "RALYL", "PCDH11X", # GABA-1 (?)
               "DRD1", "FOXP2", "EBF1", "DSCAM", "TAC1", # D1 MSN
               "DRD2", "PTPRM", "ADORA2A", "PENK" # D2 MSN
  )
  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_gaba, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(gaba_dir, sprintf("umap_%s.pdf", feat)), gg, base_height = 5, base_width = 5)
  })
  
}
```

```{r fig.height=8}
DotPlot(obj_gaba, features = features, group.by = res_to_use_sub) + coord_flip()

```

### Filter outliers

```{r}
to_exclude = c(11)
cells = Cells(obj_gaba)[!(obj_gaba@meta.data[,res_to_use_sub] %in% to_exclude)]
obj_gaba = subset(obj_gaba, cells=cells)
```

### Re process

```{r}
fname_int_ex = file.path(out_dir, "obj_gabaergic_filt.qs")
rna_dims = 10
names(dims.use_list) = map_chr(dims.use_list, max)
cluster_prefix_cur =  str_interp("${cluster_prefix}_gaba")

redo = F
if (redo) {

   obj_gaba <- obj_gaba %>%
    SCTransform(vars.to.regress = "perc_mito") %>% 
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )
  
  obj_gaba = obj_gaba %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.1, .8, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")
  
  
 
  qsave(obj_gaba, fname_int_ex)
  
} else {
  obj_gaba = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_gaba@meta.data)), value = T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_gaba, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })

DimPlot(obj_gaba, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_gaba, group.by="position", reduction=reduction_cur)
```

```{r fig.height=10}
ct_res = clustree::clustree(obj_gaba, prefix=paste(cluster_prefix_cur, "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.7")
```

```{r}
if (redo_plot) {
  #obj_gaba = RunALRA(obj_gaba, assay="RNA")
  reduction = "umap_rna"
  features = c("nCount_RNA", "nFeature_RNA", "SPEF2", "SLC17A6", "SLC17A7", "SLC17A8", "GAD1", "SLC1A2",  "MBP", "PDGFRA", 
               "NECTIN3", "SOX4",
               "CXCR4", # CR
               "ARX", "MAFB", "MAF", "LHX6", "SST", "NPY", "NXPH1", "CEMIP", "TTLL5", "SOX6", "SATB1",  ## MGE
               "LHX8", # GABA-8 
               "CALB2", # GABA-7
               "LAMP5", "CCK",  "VIP",
               "ADAMTS19", # GABA_5-3
               "PROX1", "NR2F2", "ADARB2", "CNR1", "RELN", # CGE
               "FOXP1", "TSHZ1", "ZFHX4", # LGE
               "MEIS2", "SORCS3", "IQSEC1", "TRPM3", "LRP1B", "RALYL", "PCDH11X", # GABA-1 (?)
               "DRD1", "FOXP2", "EBF1", "DSCAM", "TAC1", # D1 MSN
               "DRD2", "PTPRM", "ADORA2A", "PENK" # D2 MSN
  )
  walk(features, function(feat) {
  gg = FeaturePlot_scCustom(obj_gaba, features=feat, reduction=reduction) + coord_equal()
  print(gg)
  save_plot(file.path(gaba_dir, sprintf("umap_%s.pdf", feat)), gg, base_height = 5, base_width = 5)
})

}
```

```{r fig.height=8}
DotPlot(obj_gaba, features = features, group.by = res_to_use_sub) + coord_flip()

```

```{r}
idents_comb = c(`0`="GABA-3",
                `1`="GABA-1-1",
                `2`="GABA-1-1",
                `3`="GABA-2-1",
                `4`="GABA-1-2",
                `5`="GABA-4-1",
                `6`="GABA-2-2",
                `7`="GABA-6",
                `8`="GABA-4-2",
                `9`="GABA-5-2",
                `10`="GABA-2-3",
                `11`="GABA-5-1",
                `12`="GABA-Pre",
                `13`="GABA-1-1",
                `14`="GABA-8",
                `15`="GABA-7"
                )

out_cluster_cur = str_interp("celltype_n_gaba")
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj_gaba@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj_gaba@meta.data[,res_to_use_sub], from = names(idents_comb), to = idents_comb)
```

```{r}
qsave(obj_gaba, fname_int_ex)
```

## Non-neuronal

```{r}
nn_dir = file.path(out_dir, "nonneuronal")
dir.create(nn_dir)
```

```{r}
fname_int_ex = file.path(out_dir, "obj_nonneuronal.qs")
rna_dims = 10
cluster_prefix_cur =  str_interp("${cluster_prefix}_nn")

redo = F
if (redo) {
  cells = Cells(obj)[!grepl("GABA|Glut", obj$celltype)]
  obj_nn = subset(obj, cells=cells)
  
  obj_nn = obj_nn %>%
    SCTransform(vars.to.regress="perc_mito") %>% 
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )
  
  obj_nn = obj_nn %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.1, .8, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")
  

  
  qsave(obj_nn, fname_int_ex)
  
} else {
  obj_nn = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_nn@meta.data)), value = T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_nn, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })


DimPlot(obj_nn, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_nn, group.by="position", reduction=reduction_cur)

```

```{r fig.height=10}
ct_res = clustree::clustree(obj_nn, prefix=paste(cluster_prefix_cur, "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.8")
```

```{r}
if (redo_plot) {
  reduction = "umap_rna"
  features = c("nCount_RNA", "nFeature_RNA", "SLC17A6", "GAD1", "SLC1A2", "CSF1R", "MBP", "PLP1",
               "PDGFRA", "NECTIN3", "SOX4", "FLI1", "SPEF2", "RGS5", "NR2E1", "EOMES", "NEUROD1", "NEUROG1"
  )

  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_nn, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(glut_dir, sprintf("umap_%s.png", feat)), gg)
  })
  
  DotPlot(obj_nn, features = features, group.by = res_to_use_sub) + coord_flip()
}
```

### Filter outliers

```{r}
to_exclude = c(7, 10, 11, 15, 18)
cells = Cells(obj_nn)[!(obj_nn@meta.data[,res_to_use_sub] %in% to_exclude)]
obj_nn_filt = subset(obj_nn, cells=cells)
```

### Re-process

```{r}
fname_int_ex = file.path(out_dir, "obj_nonneuronal_filt.qs")
rna_dims = 10
cluster_prefix_cur =  str_interp("${cluster_prefix}_nn")

redo = F
if (redo) {
  obj_nn_filt = obj_nn_filt %>%
    SCTransform(vars.to.regress = "perc_mito") %>%
    RunPCA(verbose = T) %>%
    RunUMAP(  
      reduction = "pca",
      dims = 1:rna_dims,
      reduction.name = "umap_rna",
      verbose = TRUE
    )
  
  obj_nn_filt = obj_nn_filt %>% 
    seurat_find_clusters(dims.use=1:rna_dims, 
                         ress = seq(.1, .8, .1), 
                         reduction="pca",
                         algorithm = 2,
                         graph.name = NULL,
                         cluster_prefix = paste(cluster_prefix_cur, "pca", sep="_"), 
                         assay="SCT")

  qsave(obj_nn_filt, fname_int_ex)
  
} else {
  obj_nn_filt = qread(fname_int_ex)
}
```

```{r}
reduction_cur = "umap_rna"
ress = grep(cluster_prefix_cur, unique(colnames(obj_nn_filt@meta.data)), value = T)
  walk(ress, function(res) {
    print(res)
    gg = DimPlot(object = obj_nn_filt, group.by = res, label=T, reduction = reduction_cur)
    gg = gg + labs(title=res)
    print(gg)
  })

DimPlot(obj_nn_filt, group.by="assignment", reduction=reduction_cur)
DimPlot(obj_nn_filt, group.by="position", reduction=reduction_cur)
```

```{r fig.height=10}
ct_res = clustree::clustree(obj_nn_filt, prefix=paste(cluster_prefix_cur, "pca.", sep="_"), node_colour = "sc3_stability")
ct_res
```

```{r}
res_to_use_sub = str_interp("${cluster_prefix_cur}_pca.0.6")
```

```{r}
if (redo_plot) {
  reduction = "umap_rna"
  features = c("nCount_RNA", "nFeature_RNA", "SLC17A6", "GAD1", "SLC1A2", "CSF1R", "MBP", "PLP1",
               "PDGFRA", "NECTIN3", "SOX4", "FLI1", "SPEF2", "RGS5", "NR2E1", "LUM", "SOX6", "PAX6", "NEUROD1", "NEUROG1", "EOMES"
  )

  walk(features, function(feat) {
    gg = FeaturePlot_scCustom(obj_nn_filt, features=feat, reduction=reduction) + coord_equal()
    print(gg)
    save_plot(file.path(nn_dir, sprintf("umap_%s.png", feat)), gg)
  })
  
  DotPlot(obj_nn_filt, features = features, group.by = res_to_use_sub) + coord_flip()
}
```

```{r}
idents_comb = c(`0`="Astro-1",
                `1`="Astro-2",
                `2`="Astro-3",
                `3`="Oligo-1",
                `4`="OPC",
                `5`="Oligo-2",
                `6`="Glut-Pre-1",
                `7`="OPC",
                `8`="Epen",
                `9`="Astro-1",
                `10`="Oligo-3",
                `11`="Micro",
                `12`="Endo",
                `13`="OPC",
                `14`="OPC", 
                `15`="Exclude"
                )

out_cluster_cur = str_interp("celltype_nn")
out_cluster_cur_sym = as.symbol(out_cluster_cur)
obj_nn_filt@meta.data[,out_cluster_cur] <- plyr::mapvalues(x = obj_nn_filt@meta.data[,res_to_use_sub], from = names(idents_comb), to = idents_comb)
```

```{r}
qsave(obj_nn_filt, fname_int_ex)
```

## Add cluster info to main

```{r}

final_cluster = "cluster"

obj_list_sub = list(n_glut_arco = obj_glut_arco_filt, n_glut_nido = obj_glut_nido_filt, n_gaba = obj_gaba, nn=obj_nn_filt)
md = map(seq_along(obj_list_sub), function(i) {
  cluster_suffix = names(obj_list_sub)[i]
  final_cluster_cur = str_interp("celltype_${cluster_suffix}")
  md_cur = obj_list_sub[[i]]@meta.data %>% 
    filter(!!as.symbol(final_cluster_cur) != "Exclude") %>% 
    dplyr::rename(!!as.symbol(final_cluster) := !!as.symbol(final_cluster_cur)) 
  print(dim(md_cur))
  md_cur
}) %>% bind_rows()

table(md[,final_cluster])
table(md %>% dplyr::select(assignment, one_of(final_cluster)))

tab = table(md %>% dplyr::select(assignment, one_of(final_cluster)))
tab_prop = sweep(tab, 1, STATS = rowSums(tab), "/")
tab
round(tab_prop, 2)
```

```{r}
obj = AddMetaData(obj, md)
cells = Cells(obj)[!is.na(obj@meta.data[,final_cluster])]

obj_filt = subset(obj, cells=cells)
table(FetchData(obj_filt, final_cluster))
```

## Process RAW

```{r}
options(future.globals.maxSize=50 * 1E9)
```

```{r}
obj_filt[["SCT_CB"]] = obj_filt[["SCT"]]
obj_filt[["SCT_RNA"]] = obj_filt[["RNA"]]
obj_filt[["RNA"]] = obj_filt[["RAW"]]

plan(sequential)
obj_filt = obj_filt %>%
  SCTransform()

obj_filt[["SCT_RAW"]] = obj_filt[["SCT"]]
obj_filt[["RAW"]] = obj_filt[["RNA"]]
obj_filt[["RNA"]] = obj_filt[["SCT_RNA"]]
obj_filt[["SCT"]] = obj_filt[["SCT_CB"]]
```

## Final viz

```{r}
obj_filt$cluster = droplevels(obj_filt$cluster)
```

```{r}
rna_dims = 40
obj_filt = obj_filt %>%
  SCTransform(vars.to.regress = "perc_mito") %>% 
  RunPCA(verbose = T) %>%
  RunUMAP(  
    reduction = "pca",
    dims = 1:rna_dims,
    reduction.name = "umap_rna",
    verbose = TRUE
  )
```

```{r fig.height=15, fig.width=15}
reduction_cur = "umap_rna"
FeaturePlot_scCustom(obj_filt, 
            features=c("MAFB", "EMX2", "SIX2", "NDNF"), 
            reduction=reduction_cur)
DefaultAssay(obj_filt) = "SCT_RAW"
FeaturePlot_scCustom(obj_filt, 
            features=c("MAFB", "EMX2", "SIX2", "NDNF"), 
            reduction=reduction_cur)
```

```{r fig.height = 10}
reduction_cur = "umap_rna"
DimPlot(obj_filt, group.by=final_cluster, reduction=reduction_cur, label=T)
DimPlot(obj_filt, group.by="position", reduction=reduction_cur, label=T)
DimPlot(obj_filt, group.by="assignment", reduction=reduction_cur, label=F)
```

## Save object

```{r}
qsave(obj_filt, file = out_fname)
SaveH5Seurat(obj_filt, out_h5_fname, overwrite = T)
```

## Write out cell barcodes

