---
title: "Untitled"
format: html
---


```{r}
library(tidyverse)
library(Seurat)
library(SeuratDisk)
library(harmony)
library(SeuratWrappers)
library(scCustomize)
library(qs)
library(parallel)
library(cowplot)
library(rlang)
library(ComplexHeatmap)
library(scales)
library(circlize)
library(biomaRt)
library(AnnotationHub)
library(Matrix.utils)
library(doParallel)
library(foreach)



source("~/nest/rstudio/utils/stats.R")
source("~/nest/rstudio/utils/gene_lists.R")
source("~/nest/rstudio/utils/common_aesthetics.R")
```

```{r}
## CellBender
base_dir = "/hdd/brad/rstudio/snRNA/snrna_cellranger/snrna_seurat_cellbender.0.01_preprocess"
script_name = "integration/snrna_zaremba-chk_integration_glut_cellbender"
out_dir = file.path(base_dir, script_name)
dir.create(out_dir)

obj_merged_fname = file.path(out_dir, "obj_merge.rds")
obj_integrated_fname = file.path(out_dir, "obj_int.rds")
obj_integrated_fname = file.path(out_dir, "obj_int.rds")
obj_nido_integrated_fname = file.path(out_dir, "obj_nido_int.rds")

bf_fname = file.path(base_dir, "obj_clustered.qs")
bf_out_fname = file.path(out_dir, "obj_bf.qs")
chk_fname = "/hdd/sc_datasets/zaremba_gg_dev_2024/Gg_adult_snRNA_seq_srt.rds"
chk_out_fname = file.path(out_dir, "obj_chk.qs")

ortho_fname = file.path(base_dir, "integration", "oma_orthologs_zf-ck.txt")
set.seed(10)

options(future.globals.maxSize = 50 * 1E9)
```

## Process
```{r}
redo = F
load_data = F
if (redo) {
  ## Load orthologs 
  oma = read_delim(ortho_fname)
  
  ## Process BF
  obj_bf = qread(bf_fname)
  DefaultAssay(obj_bf) = "RNA"
  obj_bf$dataset = "bf"
  
  if (any(map_lgl(Assays(obj_bf), \(x) grepl("MAGIC", x)))) {
    assay_to_remove = Assays(obj_bf)[map_lgl(Assays(obj_bf), \(x) grepl("MAGIC", x))]
    obj_bf[[assay_to_remove]] = NULL
  }

  obj_bf[["SCT"]] = NULL
  filter1 = Cells(obj_bf)[grepl("Glut", obj_bf$cluster)]
  filter2 = Cells(obj_bf)[!grepl("Pre", obj_bf$cluster)]
  cells = Reduce(intersect, list(filter1, filter2))
  obj_bf = subset(obj_bf, cells=cells)
  qsave(obj_bf, bf_out_fname)
  
  
  ## Process chicken
  obj_chk = readRDS(chk_fname)
  ah = AnnotationHub()
  ens_gg = query(ah, c("Ensembl", "Gallus gallus", "EnsDb"))
  gg_db = ens_gg[["AH53208"]] ## Ensembl 87
  ens_df = AnnotationDbi::select(gg_db, keys = Features(obj_chk), c("SYMBOL", "GENENAME"), "GENEID")
  ens_df_filt = ens_df %>% dplyr::filter(GENENAME!="")
  
  obj_chk_mat = GetAssayData(obj_chk, assay = "RNA", layer="counts")
  obj_chk_mat = obj_chk_mat[ens_df_filt$GENEID,]
  rownames(obj_chk_mat) = ens_df_filt$GENENAME[match(rownames(obj_chk_mat), ens_df_filt$GENEID)]
  
  obj_chk_mat = obj_chk_mat[intersect(rownames(obj_chk_mat), oma$gene_name_ck),]
  rownames(obj_chk_mat) = oma$gene_name_zf[match(rownames(obj_chk_mat), oma$gene_name_ck)]
  obj_chk_mat = Matrix.utils::aggregate.Matrix(obj_chk_mat, rownames(obj_chk_mat), fun = "sum")
  
  chk_md = obj_chk@meta.data
  
  obj_chk = CreateSeuratObject(obj_chk_mat, meta.data = chk_md)
  DefaultAssay(obj_chk) = "RNA"
  obj_chk$cluster = obj_chk$anno_level_3
  obj_chk$dataset = "chk"
  
  filter1 = Cells(obj_chk)[grepl("Ex", obj_chk$cluster)]
  filter2 = Cells(obj_chk)[!grepl("Pre", obj_chk$cluster)]
  filter3 = Cells(obj_chk)[obj_chk$cluster != "Ex_TCF7L2"]
  cells = Reduce(intersect,list(filter1, filter2, filter3))
  obj_chk = subset(obj_chk, cells=cells)
  qsave(obj_chk, chk_out_fname)
  
  common_features = intersect(Features(obj_chk), Features(obj_bf))
  obj_chk_common = obj_chk[common_features,]
  obj_bf_common = obj_bf[common_features,]
  obj = merge(obj_bf_common, obj_chk_common)
  
  obj = obj %>%
    SCTransform() %>% 
    RunPCA(verbose=F)
  
  saveRDS(obj, obj_merged_fname)
} else {
  if (load_data) {
    obj = readRDS(obj_merged_fname)
  }
}
```


## Label transfer

```{r}
transfer_params = expand_grid(k.anchor = c(5),
                              k.filter = c(NA, 50, 100),
                              k.score = c(30),
                              max.features = c(200, 400))
dims_to_use = 1:20
```

```{r}
cores_to_use = min(nrow(transfer_params), 20)
```

```{r}

pred_long_fname = file.path(out_dir, "pred_long.rds")

redo = F
if (redo) {
  
  
  obj_bf = qread(bf_out_fname)
  obj_chk = qread(chk_out_fname)
  
  common_features = intersect(Features(obj_chk), Features(obj_bf))
  obj_chk_common = obj_chk[common_features,]
  obj_bf_common = obj_bf[common_features,]
  
  DefaultAssay(obj_bf_common) = "RNA"
  DefaultAssay(obj_chk_common) = "RNA"
  
  obj_bf_common[["RAW"]] = NULL
  
  obj_bf_common = obj_bf_common %>%
    NormalizeData() %>%
    FindVariableFeatures() %>%
    ScaleData() %>%
    RunPCA()
  
  obj_chk_common =  obj_chk_common %>%
    NormalizeData() %>%
    FindVariableFeatures() %>%
    ScaleData() %>%
    RunPCA()
  
  obj_chk_common = AddMetaData(obj_chk_common, FetchData(obj_chk, "anno_level_3"))
  
  nparams = nrow(transfer_params)
  pred_longs = lapply(1:nparams, function(i) {
    #pred_longs = foreach(i = 1:nparams) %dofuture% {
    
    k.anchor_cur <- transfer_params$k.anchor[i]
    k.filter_cur <- transfer_params$k.filter[i]
    k.score_cur <- transfer_params$k.score[i]
    max.features_cur <- transfer_params$max.features[i]
    
    anchors = FindTransferAnchors(reference = obj_bf_common, 
                                  normalization.method = "LogNormalize",
                                  k.anchor = k.anchor_cur,
                                  k.filter = k.filter_cur,
                                  k.score = k.score_cur,
                                  max.features = max.features_cur,
                                  reduction = "rpca",
                                  query = obj_chk_common, 
                                  dims = dims_to_use
                                  #reference.reduction = "pca"
    )
    
    predictions_cluster = TransferData(anchorset = anchors, 
                                       refdata = obj_bf_common$cluster,
                                       #weight.reduction = "rpca",
                                       dims = dims_to_use) %>%
      mutate(predicted.id_cluster = predicted.id)
    
    predictions_cluster$anno_level_3 = obj_chk_common$anno_level_3
    
    pred_long = predictions_cluster %>%
      dplyr::select(contains("prediction.score"), "anno_level_3") %>%
      dplyr::select(-prediction.score.max) %>%
      pivot_longer(-anno_level_3, names_to="col_tmp") %>%
      mutate(col1 = str_extract( col_tmp, "Glut.*$")) %>%
      mutate(cluster = gsub("\\.", "-", col1)) %>%
      mutate(k.anchor = k.anchor_cur,
             k.filter = k.filter_cur,
             k.score = k.score_cur,
             max.features = max.features_cur)
    return(pred_long)
  })
  
  pred_long = pred_longs %>% bind_rows()
  saveRDS(pred_long, pred_long_fname)
} else {
  pred_long = readRDS(pred_long_fname)
}
```


## Mean probabilities
```{r}
cluster_order = c(
                  c("Glut-HVC-1", "Glut-NC-1"),
                  c("Glut-HVC-2", "Glut-NC-4", "Glut-NC-3"),
                  c( "Glut-NC-2", "Glut-Nido-1", "Glut-Nido-2", "Glut-Nido-3"),
                   c("Glut-LMAN-1", "Glut-NR-1", "Glut-NR-3" ),
                  c("Glut-LMAN-2", "Glut-NR-4", "Glut-NR-2", "Glut-NR-5"),
                  c("Glut-RA", "Glut-Arco-1", "Glut-Arco-2", "Glut-Arco-3", "Glut-Arco-4", "Glut-Arco-5"))
```

```{r}
# pred_long = predictions_cluster %>%
#   dplyr::select(contains("prediction.score"), "anno_level_3") %>%
#   dplyr::select(-prediction.score.max) %>%
#   pivot_longer(-anno_level_3, names_to="col_tmp") %>%
#   mutate(col1 = str_extract( col_tmp, "Glut.*$")) %>%
#   mutate(cluster = gsub("\\.", "-", col1)) 
pred_long_sum = pred_long %>%
  ungroup() %>% 
  group_by(anno_level_3, cluster, k.anchor, k.filter, k.score, max.features) %>%
  dplyr::summarize(value_mean = mean(value),
                   value_median = median(value),
            value_sem = sem(value)) %>%
  mutate(param_set = paste(k.anchor, k.filter, k.score, max.features, sep="_"))

pred_long_split = split(pred_long_sum, pred_long_sum$param_set)

pred_long_mats = map(pred_long_split, function(pred_long_sum_cur) {
  pred_long_mat = pred_long_sum_cur %>%
    ungroup() %>% 
    dplyr::select(-value_sem, -value_median, -k.anchor, -k.filter, -k.score, -max.features, -param_set) %>%
    pivot_wider(names_from = "cluster", values_from = "value_mean") %>%
    column_to_rownames("anno_level_3") %>%
    as.matrix() %>%
    t()
  
  pred_long_mat = pred_long_mat[intersect(cluster_order, rownames(pred_long_mat)),]
  pred_long_mat
})


```

```{r}
colors_df = data.frame(cluster = cluster_order) %>%
  mutate(col = case_when(grepl("HVC", cluster) ~ position_colors["hvc"],
                         grepl("NC|Nido", cluster) ~ position_colors["ncl"],
                         grepl("LMAN", cluster) ~ position_colors["lman"],
                         grepl("NR", cluster) ~ position_colors["nido"],
                         grepl("RA", cluster) ~ position_colors["ra"],
                         grepl("Arco", cluster) ~ position_colors["arco"]))
# colors_df = data.frame(cluster = c("Glut-HVC-1", "Glut-NC-1", "Glut-NC-2", "Glut-NC-3"
#                                    "Glut-HVC-3", "Glut-Nido-3",
#                                    "Glut-LMAN-1", "Glut-NR-2",
#                                    "Glut-LMAN-2", "Glut-NR-3",
#                                    "Glut-RA", "Glut-Arco-1"),
#                        col = position_colors[c("hvc", "ncl", "hvc", "ncl", 
#                                                 "lman", "nido", "lman", "nido", "ra", "arco")])
```



#### Heatmap with bar
```{r}
pred_long_sum2 = pred_long_sum %>%
  group_by(cluster, param_set, k.anchor, k.filter, k.score, max.features) %>%
  summarize(value_mean_sum = sum(value_mean),
            value_mean_max = max(value_mean),
            value_median_max = max(value_median)) %>%
  left_join(colors_df) %>%
  mutate(cluster = factor(cluster, levels=rev(cluster_order))) 
```

```{r}

walk(names(pred_long_mats), function(param_set_cur) {
  pred_long_mat = pred_long_mats[[param_set_cur]]
  pred_long_sum2_cur = pred_long_sum2 %>% 
    dplyr::filter(param_set == param_set_cur)
  ncolors=9
  cols = colorRamp2(breaks = seq(0,1,length.out=ncolors), 
                    colors = brewer_pal(palette = "Greys")(ncolors))
  
  ncols = ncol(pred_long_mat)
  height_box = .05
  height = height_box * ncols
  width = height * ncols / nrow(pred_long_mat)
  hm = Heatmap(pred_long_mat, 
               col=cols, 
               border = T,
               name = param_set_cur,
               cluster_rows = F,
               column_names_gp = gpar(fontsize=6),
               show_column_dend = F,
               row_names_gp = gpar(fontsize=6),
               row_names_side = "left",
               clustering_method_columns = ,
               height = unit(height, "in"),
               width = unit(width, "in"))
  hm
  
  
  vals = pred_long_sum2_cur %>%
    ungroup() %>% 
    dplyr::select(value_mean_sum) %>% c() %>%  unlist()
  bar_cols =  pred_long_sum2_cur$col
  names(vals) = pred_long_sum2_cur$cluster
  names(bar_cols) = pred_long_sum2_cur$cluster
  
  vals = vals[intersect(cluster_order, names(vals))]
  bar_cols = bar_cols[intersect(cluster_order, names(bar_cols))]
  #df_cur = pred_long_sum2 %>% dplyr::select(value_mean_sum)
  ab = anno_barplot(vals, 0, which = "row", border=F, gp = gpar(fill=bar_cols))
  hm_row = HeatmapAnnotation(ab=ab, which="row")
  hm2 = hm + hm_row
  hm2
  
  print(hm2)
  pdf(file.path(out_dir, str_interp("prob_with-sum_${param_set_cur}.pdf")), 
      height = height + 2, width = width + 6)
  print(hm2)
  dev.off()
})

```

```{r}
walk(names(pred_long_mats), function(param_set_cur) {
  pred_long_mat = pred_long_mats[[param_set_cur]]
  pred_long_sum2_cur = pred_long_sum2 %>% 
    dplyr::filter(param_set == param_set_cur)
  ncolors=9
  cols = colorRamp2(breaks = seq(0,1,length.out=ncolors), colors = brewer_pal(palette = "Greys")(ncolors))
  
  ncols = ncol(pred_long_mat)
  height_box = .06
  height = height_box * ncols
  width = height * ncols / nrow(pred_long_mat)
  hm = Heatmap(pred_long_mat, 
               col=cols, 
               name = param_set_cur,
               border = T,
               cluster_rows = F,
               column_names_gp = gpar(fontsize=6),
               show_column_dend = F,
               row_names_gp = gpar(fontsize=6),
               row_names_side = "left",
               clustering_method_columns = ,
               height = unit(height, "in"),
               width = unit(width, "in"))
  hm
  
  vals = pred_long_sum2_cur %>% ungroup()%>% 
    dplyr::select(value_mean_max) %>% c() %>%  unlist()
  bar_cols =  pred_long_sum2_cur$col
  names(vals) = pred_long_sum2_cur$cluster
  names(bar_cols) = pred_long_sum2_cur$cluster
  
  vals = vals[intersect(cluster_order, names(vals))]
  bar_cols = bar_cols[intersect(cluster_order, names(bar_cols))]
  #df_cur = pred_long_sum2 %>% dplyr::select(value_mean_max)
  ab = anno_barplot(vals, 0, which = "row", border=F, gp = gpar(fill=bar_cols))
  hm_row = HeatmapAnnotation(ab=ab, which="row")
  hm2 = hm + hm_row
  print(hm2)
  pdf(file.path(out_dir, str_interp("prob_with-max_${param_set_cur}.pdf")), 
      height = height + 2, width = width + 6)
  print(hm2)
  dev.off()
})
```
```{r}
walk(names(pred_long_mats), function(param_set_cur) {
  pred_long_sum2_cur = pred_long_sum2 %>% 
    dplyr::filter(param_set == param_set_cur)
  pred_long_sum3 = pred_long_sum2_cur %>% 
    mutate(position2 = names(position_colors)[match(col, position_colors)]) %>%
    mutate(position2 = factor(position2, levels=c("hvc", "ncl", "lman", "nido", "ra", "arco"),
                              labels = c("HVC", "NC", "LMAN", "NR", "RA", "Arco")))
  
  pred_long_sum4 = pred_long_sum3 %>%
    ungroup() %>% 
    group_by(position2, col) %>%
    summarize(value_mean_max_mean = mean(value_mean_max))
  gg = ggplot(pred_long_sum3, aes(position2, value_mean_max)) +
    geom_bar(aes(y=value_mean_max_mean, fill=col), data=pred_long_sum4, stat = "identity") + 
    #geom_point(color="black", position=position_jitter(), size=.5) +
    scale_fill_identity() + 
    labs(x="", y="") + 
    theme_classic() + 
    
    theme(axis.text = element_text(size=6),
          axis.text.x = element_text(angle=90, vjust=.5, hjust=1))
  gg
  save_plot(file.path(out_dir, str_interp("max_mean_by_position_${param_set_cur}.pdf")), gg, base_width=1.5, base_height = 1.5)
})
```

```{r}
pred_long_sum2 = pred_long_sum %>%
  group_by(cluster) %>%
  summarize(value_mean_sum = sum(value_mean),
            value_mean_max = max(value_mean),
            value_median_max = max(value_median)) %>%
  left_join(colors_df) %>%
  mutate(cluster = factor(cluster, levels=rev(cluster_order))) 
```

## Integrate
```{r}
redo = F

assay_to_use = "RNA"
if (redo) {
  
  obj = readRDS(obj_merged_fname)
  DefaultAssay(obj) = assay_to_use
  
  obj = obj %>% 
    NormalizeData() %>% 
    FindVariableFeatures() %>% 
    ScaleData() %>% 
    RunPCA()
  
  rna_dims_list = seq(20, 30, 10)
  ints = c(
    "rpca"
  )
  
  # thetas = c(1, 10, 100)
  # for (theta in thetas) {
  #   print(str_interp("Harmony: theta ${theta}"))
  #   obj = obj %>%
  #     IntegrateLayers(method=HarmonyIntegration, 
  #                     orig.reduction="pca", 
  #                     new.reduction=str_interp("pca_harmony_theta${theta}"),
  #                     theta=theta
  #     )
  # }
  
  ks = c(5)
  for (k in ks) {
    print(str_interp("RPCA: k.anchor ${k}"))
    obj = obj %>%
      IntegrateLayers(method=RPCAIntegration, 
                      orig.reduction="pca",
                      new.reduction=str_interp("pca_rpca_k${k}"),
                      k.anchor=k, k.filter = NA, k.score = 30, max.features = 400,
                      normalization.method="LogNormalize")
  }
  
  for (int in ints) {
    DefaultAssay(obj) = assay_to_use
    #res = mclapply(rna_dims_list, mc.cores=length(rna_dims_list), \(rna_dims) {
    res = lapply(rna_dims_list, \(rna_dims) {
      
      if (int %in% c("rpca", "mnn", "cca")) {
        out = list2()
        for (k in ks) {
          umap_name = str_interp("umap_rna_${int}_k${k}_${rna_dims}")
          obj =  RunUMAP(
            object = obj,
            reduction = str_interp("pca_${int}_k${k}"),
            reduction.name = umap_name,
            assay = assay_to_use,
            dims = 1:rna_dims,
            verbose = TRUE
          )
          out = c(out, list2(!!umap_name := obj@reductions[[umap_name]]))
        }
      } else  if (int %in% c("harmony")) {
        out = list2()
        for (theta in thetas) {
          umap_name = str_interp("umap_rna_${int}_theta${theta}_${rna_dims}")
          obj =  RunUMAP(
            object = obj,
            reduction = str_interp("pca_${int}_theta${theta}"),
            reduction.name = umap_name,
            assay = assay_to_use,
            dims = 1:rna_dims,
            verbose = TRUE
          )
          out = c(out, list2(!!umap_name := obj@reductions[[umap_name]]))
        }
      }  else {
        umap_name = str_interp("umap_rna_${int}_${rna_dims}")
        obj =  RunUMAP(
          object = obj,
          reduction = str_interp("pca_${int}"),
          reduction.name = umap_name,
          assay = assay_to_use,
          dims = 1:rna_dims,
          verbose = TRUE
        )
         out = list(umaps = obj@reductions[[umap_name]])
         names(out) = c(umap_name)
         
      }
      return(out)
      
    }) %>% set_names(rna_dims_list)
    
    for (rna_dims in as.character(rna_dims_list)) {
      res_cur = res[[rna_dims]]
      if (int %in% c("rpca", "mnn", "harmony")) {
        for (i in seq_along(res_cur)) {
          obj[[names(res_cur)[i]]] = res_cur[[i]]
        }
      } else {
        #obj = AddMetaData(obj, res_cur$clusters)
        umap_name = names(res_cur)[1]
        obj[[umap_name]] = res_cur[[umap_name]]
      }
    }
  }
  
  qsave(obj, obj_integrated_fname)
  
} else {
  obj = qread(obj_integrated_fname)
}
```

### Plots
```{r}
redo_plot = T
if (redo_plot) {
  reductions = Reductions(obj)
  reductions = grep("umap", reductions, value=T)
  #reductions = c("umap_weighted_rna40_atac20")
  cats = c("dataset", "cluster")
  
  walk(reductions, function(reduction) {
    walk(cats, function(ca) {
      gg = DimPlot_scCustom(obj, group.by=ca, reduction = reduction,
                            figure_plot = T, label=T, label.size = 2,
                            raster = T, raster.dpi = c(1024, 1024),
                            pt.size=2, aspect_ratio = 1) + coord_equal()
      print(gg)
      save_plot(file.path(out_dir, sprintf("%s_%s.png", reduction, ca)), gg)
    })
  })
}
```

```{r}
redo_plot = T
if (redo_plot) {
  reductions = Reductions(obj)
  reductions = grep("umap", reductions, value=T)
  #reductions = c("umap_weighted_rna40_atac20")
  cats = c("dataset", "cluster")
  
  walk(reductions, function(reduction) {
      gg = DimPlot_scCustom(obj, group.by="cluster", split.by = "dataset", reduction = reduction,
                            figure_plot = T, label=F, label.size = 2,
                            raster = T, raster.dpi = c(1024, 1024),
                            pt.size=2, aspect_ratio = 1) + coord_equal()
      print(gg)
      save_plot(file.path(out_dir, sprintf("%s_cluster_split-by-dataset.pdf", reduction)), gg, ncol=3, base_height = 3)
    })
}
```
